From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedArrivalSequence.

Check Lean.Nat.
Check ImportedArrivalSequence.Prosa_Behavior_Time_instant.
Check ImportedArrivalSequence.Prosa_Behavior_Job_JobArrival.
Check ImportedArrivalSequence.Prosa_Behavior_Job_JobArrival_mk.
Check ImportedArrivalSequence.Prosa_Behavior_Job_JobArrival_job_arrival.
Check ImportedArrivalSequence.Prosa_Util_Notation_bigCat.
Check ImportedArrivalSequence.List_filter.
Check ImportedArrivalSequence.List_Nodup.

Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrival_sequence.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrivals_at.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrives_at.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrives_in.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_consistent_arrival_times.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrival_sequence_uniq.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_valid_arrival_sequence.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_has_arrived.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrived_before.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrived_between.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrivals_between.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrivals_up_to.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrivals_before.
Check ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrivals_between_P.

Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrival_sequence.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrivals_at.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrives_at.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrives_in.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_consistent_arrival_times.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrival_sequence_uniq.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_valid_arrival_sequence.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_has_arrived.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrived_before.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrived_between.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrivals_between.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrivals_up_to.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrivals_before.
Print ImportedArrivalSequence.Prosa_Behavior_Arrival_sequence_arrivals_between_P.
