From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedSupply.

Check ImportedSupply.Prosa_Model_Processor_Supply_supply_at.
Check ImportedSupply.Prosa_Model_Processor_Supply_supply_during.
Check ImportedSupply.Prosa_Model_Processor_Supply_has_supply.
Check ImportedSupply.Prosa_Model_Processor_Supply_is_blackout.
Check ImportedSupply.Prosa_Model_Processor_Supply_blackout_during.

Check ImportedSupply.Prosa_Validation_SupplyInterface_supplyAtProjection.
Check ImportedSupply.Prosa_Validation_SupplyInterface_supplyDuringProjection.
Check ImportedSupply.Prosa_Validation_SupplyInterface_hasSupplyProjection.
Check ImportedSupply.Prosa_Validation_SupplyInterface_isBlackoutProjection.
Check ImportedSupply.Prosa_Validation_SupplyInterface_blackoutDuringProjection.

Check ImportedSupply.Prosa_Validation_ScheduleInterface_coreEnumeration.
Check ImportedSupply.Prosa_Validation_ScheduleInterface_production_supply_in_as_list_sum.
