From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedFinishTime.

Set Printing All.
Set Printing Width 110.

Check ImportedFinishTime.Prosa_Analysis_Definitions_FinishTime_finish_time.
Print ImportedFinishTime.Prosa_Analysis_Definitions_FinishTime_finish_time.

Check ImportedFinishTime.Prosa_Analysis_Definitions_FinishTime_finished_at_finish_time.
Print ImportedFinishTime.Prosa_Analysis_Definitions_FinishTime_finished_at_finish_time.

Check ImportedFinishTime.Prosa_Analysis_Definitions_FinishTime_earliest_finish_time.
Print ImportedFinishTime.Prosa_Analysis_Definitions_FinishTime_earliest_finish_time.

Check ImportedFinishTime.Prosa_Analysis_Definitions_FinishTime_completes_at_finish_time.
Print ImportedFinishTime.Prosa_Analysis_Definitions_FinishTime_completes_at_finish_time.

Check ImportedFinishTime.Prosa_Analysis_Definitions_FinishTime_response_time.
Print ImportedFinishTime.Prosa_Analysis_Definitions_FinishTime_response_time.
