(* Classic validation list library over the universe instance [List_inst1] (mechanical renaming of the
   core/mem/uniq parts: [I.List*] -> [I.List*_inst1], [cl_*] -> [cl1_*], [ClListRel] -> [ClListRel1]); (generated by scripts/classic_listops.py from the accepted
   certificates/classic_util_list/ClassicListOps.v, re-bound to this export).  Features: core mem uniq (universe instance List_inst1) *)
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedClassicExtractionTdma.
From FoundationCertificates Require Import PropSPropFoundation LogicalRelation
  SubadditivityNatCorrespondence ClassicExtractionTdmaBase.



Module I := ImportedClassicExtractionTdma.

(** Sequences are related to Lean lists through an element conversion [c]
    (the identity for identified carriers, the pair conversion for pairs):
    [ClListRel c sR sL := Lean.eq (cl_map c sR) sL].  Every operation lemma
    relates the MathComp operation on [sR] to the Lean operation on the
    converted list, by structural induction; the Lean side is unfolded one
    constructor at a time by conversion only. *)

Lemma cl1_nat_logic nR nL : SubNatRel nR nL -> Logic.eq nL (sub_nat_to_imported nR).
Proof. intro H. exact (Logic.eq_sym (imported_eq_to_coq_eq _ _ H)). Qed.

Lemma cl1_nat_input nR nL : SubNatRel nR nL -> Logic.eq (sub_nat_to_rocq nL) nR.
Proof. intro H. rewrite (cl1_nat_logic _ _ H). exact (sub_nat_rocq_roundtrip nR). Qed.

Lemma cl1_lean_eq (A : Type) (x y : A) : Logic.eq x y -> Lean.eq x y.
Proof. exact (coq_eq_to_imported_eq x y). Qed.

(* ------------------------------------------------------------------ *)
(** * Conversions *)

Fixpoint cl1_map {A B : Type} (c : A -> B) (s : seq A) : I.List_inst1 B :=
  match s with [::] => I.List_nil_inst1 B | x :: s' => I.List_cons_inst1 B (c x) (cl1_map c s') end.

Fixpoint cl1_unmap {A B : Type} (d : B -> A) (l : I.List_inst1 B) : seq A :=
  match l with I.List_nil_inst1 => [::] | I.List_cons_inst1 x l' => d x :: cl1_unmap d l' end.

Lemma cl1_unmap_map {A B : Type} (c : A -> B) (d : B -> A) (Hdc : forall x, Logic.eq (d (c x)) x) s :
  Logic.eq (cl1_unmap d (cl1_map c s)) s.
Proof. elim: s => [|x s IH] //=. by rewrite Hdc IH. Qed.

Lemma cl1_map_unmap {A B : Type} (c : A -> B) (d : B -> A) (Hcd : forall y, Logic.eq (c (d y)) y) l :
  Logic.eq (cl1_map c (cl1_unmap d l)) l.
Proof. induction l as [|y l IH]; first reflexivity. cbn. by rewrite Hcd IH. Qed.

Definition ClListRel1 {A B : Type} (c : A -> B) (sR : seq A) (sL : I.List_inst1 B) : SProp := Lean.eq (cl1_map c sR) sL.

Lemma cl1_list_logic {A B} (c : A -> B) sR sL : ClListRel1 c sR sL -> Logic.eq sL (cl1_map c sR).
Proof. intro H. exact (Logic.eq_sym (imported_eq_to_coq_eq _ _ H)). Qed.

Lemma cl1_forall_list {A B : Type} (c : A -> B) (d : B -> A) (Hcd : forall y, Logic.eq (c (d y)) y)
    (PR : seq A -> Prop) (PL : I.List_inst1 B -> SProp) :
  (forall sR sL, ClListRel1 c sR sL -> PropSPropRel (PR sR) (PL sL)) ->
  PropSPropRel (forall s, PR s) (forall s, PL s).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros HR sL.
    exact (prop_to_sprop _ _ (H _ _ (cl1_lean_eq _ _ _ (cl1_map_unmap c d Hcd sL))) (HR _)).
  - intro HL. apply strictly_inhabits. intro sR.
    exact (sprop_to_prop _ _ (H sR (cl1_map c sR) (@Lean.eq_refl _ _)) (HL _)).
Qed.

(* ------------------------------------------------------------------ *)
(** * Membership, uniqueness, index (eqTypes) *)

Section Eq.
Variables (A : eqType) (B : Type) (c : A -> B) (d : B -> A).
Hypothesis Hdc : forall x, Logic.eq (d (c x)) x.
Hypothesis Hcd : forall y, Logic.eq (c (d y)) y.

Lemma cl1_c_inj x y : Logic.eq (c x) (c y) -> Logic.eq x y.
Proof. move=> E. by rewrite -(Hdc x) -(Hdc y) E. Qed.

Definition cl1_false_elim_s (Q : SProp) (H : is_true false) : Q :=
  match (Bool.diff_false_true H) return Q with end.

End Eq.

Section EqU.
Variables (A : eqType) (B : Type) (c : A -> B) (d : B -> A).
Hypothesis Hdc : forall x, Logic.eq (d (c x)) x.
Hypothesis Hcd : forall y, Logic.eq (c (d y)) y.

End EqU.


