(* Classic validation base (generated by scripts/classic_base.py from the accepted
   certificates/classic_util_tactics/ClassicTacticsCorrespondence.v, re-bound to this export).
   Features: bool sub min eqtype logic forall *)
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat.
From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedClassicInterferenceBoundGlobal.
From FoundationCertificates Require Import PropSPropFoundation LogicalRelation
  SubadditivityNatCorrespondence.

Module I := ImportedClassicInterferenceBoundGlobal.

Definition ct_b2l (b : bool) : I.Bool := if b then I.Bool_true else I.Bool_false.
Definition ct_l2b (b : I.Bool) : bool := match b with I.Bool_true => true | I.Bool_false => false end.
Definition CtBoolRel (bR : bool) (bL : I.Bool) : SProp := Lean.eq (ct_b2l bR) bL.

Lemma ct_bool_canonical b : CtBoolRel b (ct_b2l b).
Proof. exact (@Lean.eq_refl _ _). Qed.

Lemma ct_bool_surjective b : CtBoolRel (ct_l2b b) b.
Proof. destruct b; exact (@Lean.eq_refl _ _). Qed.

Lemma ct_bool_rel_logic bR bL : CtBoolRel bR bL -> Logic.eq bL (ct_b2l bR).
Proof. intro H. exact (Logic.eq_sym (imported_eq_to_coq_eq _ _ H)). Qed.

Definition ct_false_elim (Q : SProp) (H : I.False) : Q := match H return Q with end.
Definition ct_coq_false_to_target (H : Logic.False) : I.False := match H return I.False with end.
Definition ct_target_false_to_strict (H : I.False) : StrictlyInhabited Logic.False := match H with end.

Definition ct_sub (a b : Lean.Nat) : Lean.Nat :=
  I.HSub_hSub_inst7 Lean.Nat Lean.Nat Lean.Nat (I.instHSub_inst1 Lean.Nat I.instSubNat) a b.

Lemma ct_sub_canonical (a b : nat) :
  Logic.eq (ct_sub (sub_nat_to_imported a) (sub_nat_to_imported b)) (sub_nat_to_imported (a - b)).
Proof.
  elim: b => [|b IH]; first by rewrite subn0.
  change (Logic.eq (I.Nat_pred (ct_sub (sub_nat_to_imported a) (sub_nat_to_imported b)))
                   (sub_nat_to_imported (a - b.+1))).
  rewrite IH subnS. case: (a - b) => [|k]; reflexivity.
Qed.

Lemma ct_sub_rel aR aL bR bL : SubNatRel aR aL -> SubNatRel bR bL -> SubNatRel (aR - bR) (ct_sub aL bL).
Proof.
  intros Ha Hb. rewrite -(imported_eq_to_coq_eq _ _ Ha) -(imported_eq_to_coq_eq _ _ Hb).
  apply: coq_eq_to_imported_eq. exact (Logic.eq_sym (ct_sub_canonical aR bR)).
Qed.

Lemma ct_min_canonical (a b : nat) :
  Logic.eq ((I.Min_min_inst1 Lean.Nat I.instMinNat) (sub_nat_to_imported a) (sub_nat_to_imported b)) (sub_nat_to_imported (minn a b)).
Proof.
  have Hle := sub_nat_le_correspondence _ _ _ _ (sub_nat_rel_canonical a) (sub_nat_rel_canonical b).
  have -> : Logic.eq ((I.Min_min_inst1 Lean.Nat I.instMinNat) (sub_nat_to_imported a) (sub_nat_to_imported b))
      (I.ite Lean.Nat (I.LE_le_inst1 Lean.Nat I.instLENat (sub_nat_to_imported a) (sub_nat_to_imported b))
         (I.Nat_decLe (sub_nat_to_imported a) (sub_nat_to_imported b)) (sub_nat_to_imported a) (sub_nat_to_imported b))
    by reflexivity.
  destruct (I.Nat_decLe (sub_nat_to_imported a) (sub_nat_to_imported b)) as [h|h].
  - have Hab : ~~ (a <= b)%nat.
    { apply/negP => Hs. exact (interpret_strict _ (ct_target_false_to_strict (h (prop_to_sprop _ _ Hle Hs)))). }
    rewrite -ltnNge in Hab. rewrite (minn_idPr (ltnW Hab)). reflexivity.
  - have Hab : (a <= b)%nat := sprop_to_prop _ _ Hle h. rewrite (minn_idPl Hab). reflexivity.
Qed.

Lemma ct_min_rel aR aL bR bL : SubNatRel aR aL -> SubNatRel bR bL -> SubNatRel (minn aR bR) ((I.Min_min_inst1 Lean.Nat I.instMinNat) aL bL).
Proof.
  intros Ha Hb. rewrite -(imported_eq_to_coq_eq _ _ Ha) -(imported_eq_to_coq_eq _ _ Hb).
  apply: coq_eq_to_imported_eq. exact (Logic.eq_sym (ct_min_canonical aR bR)).
Qed.

Definition ct_decidable_eq (T : eqType) : I.DecidableEq T :=
  fun x y =>
    match @eqP T x y with
    | ReflectT H => I.Decidable_isTrue (Lean.eq x y) (coq_eq_to_imported_eq x y H)
    | ReflectF H => I.Decidable_isFalse (Lean.eq x y)
        (fun HL => ct_coq_false_to_target (H (imported_eq_to_coq_eq x y HL)))
    end.

Lemma ct_eq_rel (T : Type) (x y : T) : PropSPropRel (Logic.eq x y) (Lean.eq x y).
Proof.
  apply prop_sprop_rel_intro.
  - exact (coq_eq_to_imported_eq x y).
  - intro H. exact (strictly_inhabits (imported_eq_to_coq_eq x y H)).
Qed.

Lemma ct_eqb_rel (T : eqType) (x y : T) : PropSPropRel (is_true (x == y)) (Lean.eq x y).
Proof.
  apply prop_sprop_rel_intro.
  - move=> /eqP. exact (coq_eq_to_imported_eq x y).
  - intro H. apply strictly_inhabits. apply/eqP. exact (imported_eq_to_coq_eq x y H).
Qed.

(* ct_decide_eq omitted: [Decidable.decide] is not part of this export. *)

Lemma ct_imp (P Q : Prop) (PL QL : SProp) :
  PropSPropRel P PL -> PropSPropRel Q QL -> PropSPropRel (P -> Q) (PL -> QL).
Proof.
  intros HP HQ. apply prop_sprop_rel_intro.
  - intros H p. apply (prop_to_sprop _ _ HQ). exact (H (sprop_to_prop _ _ HP p)).
  - intro H. apply strictly_inhabits. intro p.
    apply (sprop_to_prop _ _ HQ). exact (H (prop_to_sprop _ _ HP p)).
Qed.

Lemma ct_and (P Q : Prop) (PL QL : SProp) :
  PropSPropRel P PL -> PropSPropRel Q QL -> PropSPropRel (P /\ Q) (And PL QL).
Proof.
  intros HP HQ. apply prop_sprop_rel_intro.
  - intros [p q]. exact (And_intro PL QL (prop_to_sprop _ _ HP p) (prop_to_sprop _ _ HQ q)).
  - intros [p q]. apply strictly_inhabits. split.
    + exact (sprop_to_prop _ _ HP p).
    + exact (sprop_to_prop _ _ HQ q).
Qed.

Lemma ct_forall_identity (A : Type) (PR : A -> Prop) (PL : A -> SProp) :
  (forall x, PropSPropRel (PR x) (PL x)) -> PropSPropRel (forall x, PR x) (forall x, PL x).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros HR x. exact (prop_to_sprop _ _ (H x) (HR x)).
  - intro HL. apply strictly_inhabits. intro x. exact (sprop_to_prop _ _ (H x) (HL x)).
Qed.

Lemma ct_forall_bool (PR : bool -> Prop) (PL : I.Bool -> SProp) :
  (forall bR bL, CtBoolRel bR bL -> PropSPropRel (PR bR) (PL bL)) ->
  PropSPropRel (forall b, PR b) (forall b, PL b).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros HR bL. exact (prop_to_sprop _ _ (H _ _ (ct_bool_surjective bL)) (HR _)).
  - intro HL. apply strictly_inhabits. intro bR. exact (sprop_to_prop _ _ (H _ _ (ct_bool_canonical bR)) (HL _)).
Qed.

Lemma ct_forall_nat (PR : nat -> Prop) (PL : Lean.Nat -> SProp) :
  (forall nR nL, SubNatRel nR nL -> PropSPropRel (PR nR) (PL nL)) ->
  PropSPropRel (forall n, PR n) (forall n, PL n).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros HR nL. exact (prop_to_sprop _ _ (H _ _ (sub_nat_rel_surjective nL)) (HR _)).
  - intro HL. apply strictly_inhabits. intro nR. exact (sprop_to_prop _ _ (H _ _ (sub_nat_rel_canonical nR)) (HL _)).
Qed.

