import Prosa.Model.Processor.Ideal
import Validation.fixtures.translation_order.RsIwInstantiationComputationInterface

/-!
Validation-only universe witnesses for the ideal processor model: each definition applies one generic
processor-state-dependent constant of the accepted restricted-supply `iw_instantiation` export root at the ideal
processor model, so that every export whose root imports this module contains it at the ideal universe instance
(the Rocq import then provides its specialised copy, and the generic certificate helpers replay over it).  No
statement or equation is added.
-/

namespace Prosa.Validation.IdealInstWitness
open Prosa.Behavior.Job Prosa.Behavior.Schedule Prosa.Model.Processor.Ideal

noncomputable def w_Analysis_Definitions_ServiceInversion_Pred_service_inversion (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.ServiceInversion.Pred.service_inversion (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_ServiceInversion_Pred_cumulative_service_inversion (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.ServiceInversion.Pred.cumulative_service_inversion (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_ServiceInversion_Pred_pred_service_inversion_of_job_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.ServiceInversion.Pred.pred_service_inversion_of_job_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_ServiceInversion_Pred_pred_service_inversion_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.ServiceInversion.Pred.pred_service_inversion_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_Service_served_jobs_at (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.Service.served_jobs_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Service_receives_service_at (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Service.receives_service_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ServiceInversionPredInterface_cumulativeServiceInversionProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ServiceInversionPredInterface.cumulativeServiceInversionProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Preemption_Parameter_preempted_at (Job : JobType) [DecidableEq Job] := @Prosa.Model.Preemption.Parameter.preempted_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Preemption_Parameter_not_preemptive_implies_scheduled (Job : JobType) [DecidableEq Job] := @Prosa.Model.Preemption.Parameter.not_preemptive_implies_scheduled (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Preemption_Parameter_execution_starts_with_preemption_point (Job : JobType) [DecidableEq Job] := @Prosa.Model.Preemption.Parameter.execution_starts_with_preemption_point (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Preemption_Parameter_valid_preemption_model (Job : JobType) [DecidableEq Job] := @Prosa.Model.Preemption.Parameter.valid_preemption_model (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Preemption_Parameter_no_superfluous_preemptions (Job : JobType) [DecidableEq Job] := @Prosa.Model.Preemption.Parameter.no_superfluous_preemptions (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Ready_JobReady (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Ready.JobReady (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Ready_JobReady_mk (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Ready.JobReady.mk (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Ready_JobReady_job_ready (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Ready.JobReady.job_ready (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Ready_JobReady_ready_implies_pending (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Ready.JobReady.ready_implies_pending (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Service_pending (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Service.pending (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Service_completed_by (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Service.completed_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Service_service (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Service.service (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Service_service_during (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Service.service_during (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Service_service_at (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Service.service_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ScheduleInterface_coreEnumeration (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ScheduleInterface.coreEnumeration (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ScheduleInterface_production_scheduled_in_eq_true_iff (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ScheduleInterface.production_scheduled_in_eq_true_iff (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ScheduleInterface_production_service_in_as_list_sum (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ScheduleInterface.production_service_in_as_list_sum (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ServiceInterface_pendingProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ServiceInterface.pendingProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ServiceInterface_completedByProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ServiceInterface.completedByProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ServiceInterface_serviceProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ServiceInterface.serviceProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ServiceInterface_serviceDuringProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ServiceInterface.serviceDuringProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ServiceInterface_serviceAtProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ServiceInterface.serviceAtProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Service_scheduled_at (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Service.scheduled_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ServiceInterface_scheduledAtProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ServiceInterface.scheduledAtProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Ready_backlogged (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Ready.backlogged (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_Definitions_quiet_time (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.Definitions.quiet_time (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_Definitions_busy_interval_prefix (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.Definitions.busy_interval_prefix (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_Definitions_busy_interval (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.Definitions.busy_interval (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_Definitions_work_conserving (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.Definitions.work_conserving (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_Definitions_busy_intervals_are_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.Definitions.busy_intervals_are_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_Definitions_cond_interference_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.Definitions.cond_interference_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_Definitions_job_interference_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.Definitions.job_interference_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Service_pending_earlier_and_at (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Service.pending_earlier_and_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ServiceInterface_pendingEarlierAndAtProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ServiceInterface.pendingEarlierAndAtProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_AbstractDefinitionsInterface_quiet_time_eq (Job : JobType) [DecidableEq Job] := @Prosa.Validation.AbstractDefinitionsInterface.quiet_time_eq (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_RestrictedSupply_BusyPrefix_service_inversion_of_job_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.RestrictedSupply.BusyPrefix.service_inversion_of_job_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_RestrictedSupply_BusyPrefix_service_inversion_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.RestrictedSupply.BusyPrefix.service_inversion_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Processor_PlatformProperties_unit_service_proc_model (Job : JobType) [DecidableEq Job] := @Prosa.Model.Processor.PlatformProperties.unit_service_proc_model (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Ready_jobs_must_arrive_to_execute (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Ready.jobs_must_arrive_to_execute (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Ready_completed_jobs_dont_execute (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Ready.completed_jobs_dont_execute (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_AbstractRta_relative_arrival_time_of_job_is_A (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.AbstractRta.relative_arrival_time_of_job_is_A (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_AbstractRta_relative_time_to_reach_rtct (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.AbstractRta.relative_time_to_reach_rtct (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_Schedulability_task_response_time_bound (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.Schedulability.task_response_time_bound (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Service_job_response_time_bound (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Service.job_response_time_bound (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Task_Preemption_Parameters_valid_model_with_bounded_nonpreemptive_segments (Job : JobType) [DecidableEq Job] := @Prosa.Model.Task.Preemption.Parameters.valid_model_with_bounded_nonpreemptive_segments (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Processor_PlatformProperties_ideal_progress_proc_model (Job : JobType) [DecidableEq Job] := @Prosa.Model.Processor.PlatformProperties.ideal_progress_proc_model (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_IBF_Task_nonself (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.IBF.Task.nonself (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_IBF_Task_task_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.IBF.Task.task_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_IBF_Task_cumul_task_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.IBF.Task.cumul_task_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_IBF_Task_task_interference_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.IBF.Task.task_interference_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_IBF_Task_interference_and_workload_consistent_with_sequential_tasks (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.IBF.Task.interference_and_workload_consistent_with_sequential_tasks (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_TaskSchedule_scheduled_jobs_of_task_at (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.TaskSchedule.scheduled_jobs_of_task_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_TaskSchedule_task_scheduled_at (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.TaskSchedule.task_scheduled_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_TaskSchedule_task_service_at (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.TaskSchedule.task_service_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_TaskSchedule_task_service_during (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.TaskSchedule.task_service_during (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_TaskSchedule_task_service (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.TaskSchedule.task_service (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_TaskSchedule_served_jobs_of_task_at (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.TaskSchedule.served_jobs_of_task_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_TaskSchedule_task_served_at (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.TaskSchedule.task_served_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Schedule_Scheduled_scheduled_jobs_at (Job : JobType) [DecidableEq Job] := @Prosa.Model.Schedule.Scheduled.scheduled_jobs_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ServiceInterface_receivesServiceAtProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ServiceInterface.receivesServiceAtProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_TaskScheduleInterface_taskServiceDuringProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.TaskScheduleInterface.taskServiceDuringProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_TaskScheduleInterface_taskServiceProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.TaskScheduleInterface.taskServiceProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Task_Sequentiality_sequential_tasks (Job : JobType) [DecidableEq Job] := @Prosa.Model.Task.Sequentiality.sequential_tasks (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Task_Sequentiality_prior_jobs_complete (Job : JobType) [DecidableEq Job] := @Prosa.Model.Task.Sequentiality.prior_jobs_complete (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Aggregate_ServiceOfJobs_service_of_jobs_at (Job : JobType) [DecidableEq Job] := @Prosa.Model.Aggregate.ServiceOfJobs.service_of_jobs_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Aggregate_ServiceOfJobs_service_of_jobs (Job : JobType) [DecidableEq Job] := @Prosa.Model.Aggregate.ServiceOfJobs.service_of_jobs (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Aggregate_ServiceOfJobs_service_of_higher_or_equal_priority_jobs (Job : JobType) [DecidableEq Job] := @Prosa.Model.Aggregate.ServiceOfJobs.service_of_higher_or_equal_priority_jobs (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Aggregate_ServiceOfJobs_service_of_other_hep_jobs (Job : JobType) [DecidableEq Job] := @Prosa.Model.Aggregate.ServiceOfJobs.service_of_other_hep_jobs (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Aggregate_ServiceOfJobs_service_of_other_task_hep_jobs (Job : JobType) [DecidableEq Job] := @Prosa.Model.Aggregate.ServiceOfJobs.service_of_other_task_hep_jobs (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Aggregate_ServiceOfJobs_service_of_hep_jobs (Job : JobType) [DecidableEq Job] := @Prosa.Model.Aggregate.ServiceOfJobs.service_of_hep_jobs (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Aggregate_ServiceOfJobs_task_service_of_jobs_in (Job : JobType) [DecidableEq Job] := @Prosa.Model.Aggregate.ServiceOfJobs.task_service_of_jobs_in (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Aggregate_ServiceOfJobs_total_service_of_jobs_in (Job : JobType) [DecidableEq Job] := @Prosa.Model.Aggregate.ServiceOfJobs.total_service_of_jobs_in (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_IBF_SupplyTask_nonself_intra (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.IBF.SupplyTask.nonself_intra (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_IBF_SupplyTask_task_intra_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.IBF.SupplyTask.task_intra_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_IBF_SupplyTask_task_intra_interference_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.IBF.SupplyTask.task_intra_interference_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Processor_Supply_supply_at (Job : JobType) [DecidableEq Job] := @Prosa.Model.Processor.Supply.supply_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Processor_Supply_supply_during (Job : JobType) [DecidableEq Job] := @Prosa.Model.Processor.Supply.supply_during (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Processor_Supply_has_supply (Job : JobType) [DecidableEq Job] := @Prosa.Model.Processor.Supply.has_supply (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Processor_Supply_is_blackout (Job : JobType) [DecidableEq Job] := @Prosa.Model.Processor.Supply.is_blackout (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Processor_Supply_blackout_during (Job : JobType) [DecidableEq Job] := @Prosa.Model.Processor.Supply.blackout_during (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ScheduleInterface_production_supply_in_as_list_sum (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ScheduleInterface.production_supply_in_as_list_sum (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_SupplyInterface_supplyAtProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.SupplyInterface.supplyAtProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_SupplyInterface_supplyDuringProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.SupplyInterface.supplyDuringProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_SupplyInterface_hasSupplyProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.SupplyInterface.hasSupplyProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_SupplyInterface_isBlackoutProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.SupplyInterface.isBlackoutProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_SupplyInterface_blackoutDuringProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.SupplyInterface.blackoutDuringProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_IBF_Supply_intra_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.IBF.Supply.intra_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_IBF_Supply_cumul_intra_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.IBF.Supply.cumul_intra_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_IBF_Supply_intra_interference_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.IBF.Supply.intra_interference_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_RestrictedSupply_IwInstantiation_rs_jlfp_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.RestrictedSupply.IwInstantiation.rs_jlfp_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Abstract_RestrictedSupply_IwInstantiation_rs_jlfp_interfering_workload (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Abstract.RestrictedSupply.IwInstantiation.rs_jlfp_interfering_workload (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Schedule_PriorityDriven_respects_JLDP_policy_at_preemption_point (Job : JobType) [DecidableEq Job] := @Prosa.Model.Schedule.PriorityDriven.respects_JLDP_policy_at_preemption_point (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Schedule_PriorityDriven_respects_JLFP_policy_at_preemption_point (Job : JobType) [DecidableEq Job] := @Prosa.Model.Schedule.PriorityDriven.respects_JLFP_policy_at_preemption_point (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Schedule_PriorityDriven_respects_FP_policy_at_preemption_point (Job : JobType) [DecidableEq Job] := @Prosa.Model.Schedule.PriorityDriven.respects_FP_policy_at_preemption_point (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Schedule_PreemptionTime_preemption_time (Job : JobType) [DecidableEq Job] := @Prosa.Model.Schedule.PreemptionTime.preemption_time (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Schedule_Scheduled_scheduled_job_at (Job : JobType) [DecidableEq Job] := @Prosa.Model.Schedule.Scheduled.scheduled_job_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_PreemptionTimeInterface_production_preemption_time_some (Job : JobType) [DecidableEq Job] := @Prosa.Validation.PreemptionTimeInterface.production_preemption_time_some (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_PreemptionTimeInterface_production_preemption_time_none (Job : JobType) [DecidableEq Job] := @Prosa.Validation.PreemptionTimeInterface.production_preemption_time_none (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_PreemptionTimeInterface_production_scheduled_job_at_eq (Job : JobType) [DecidableEq Job] := @Prosa.Validation.PreemptionTimeInterface.production_scheduled_job_at_eq (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Processor_PlatformProperties_uniprocessor_model (Job : JobType) [DecidableEq Job] := @Prosa.Model.Processor.PlatformProperties.uniprocessor_model (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Ready_valid_schedule (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Ready.valid_schedule (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Ready_jobs_must_be_ready_to_execute (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Ready.jobs_must_be_ready_to_execute (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Ready_jobs_come_from_arrival_sequence (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Ready.jobs_come_from_arrival_sequence (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Schedule_Scheduled_is_idle (Job : JobType) [DecidableEq Job] := @Prosa.Model.Schedule.Scheduled.is_idle (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ScheduleInterface_coreEnumeration_complete (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ScheduleInterface.coreEnumeration_complete (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_ScheduleInterface_coreEnumeration_nodup (Job : JobType) [DecidableEq Job] := @Prosa.Validation.ScheduleInterface.coreEnumeration_nodup (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_BusyInterval_Classical_quiet_time (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.BusyInterval.Classical.quiet_time (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_BusyInterval_Classical_busy_interval_prefix (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.BusyInterval.Classical.busy_interval_prefix (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_BusyInterval_Classical_busy_interval (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.BusyInterval.Classical.busy_interval (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_BusyInterval_Classical_quiet_time_dec (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.BusyInterval.Classical.quiet_time_dec (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Service_completes_at (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Service.completes_at (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_PriorityInversion_priority_inversion (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.PriorityInversion.priority_inversion (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_PriorityInversion_priority_inversion_cond (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.PriorityInversion.priority_inversion_cond (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_PriorityInversion_cumulative_priority_inversion (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.PriorityInversion.cumulative_priority_inversion (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_PriorityInversion_cumulative_priority_inversion_cond (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.PriorityInversion.cumulative_priority_inversion_cond (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_PriorityInversion_priority_inversion_of_job_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.PriorityInversion.priority_inversion_of_job_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_PriorityInversion_priority_inversion_of_job_cond_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.PriorityInversion.priority_inversion_of_job_cond_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_PriorityInversion_priority_inversion_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.PriorityInversion.priority_inversion_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_PriorityInversion_priority_inversion_cond_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.PriorityInversion.priority_inversion_cond_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_PriorityInversionInterface_cumulPriorityInversionProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.PriorityInversionInterface.cumulPriorityInversionProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Validation_PriorityInversionInterface_cumulPriorityInversionCondProjection (Job : JobType) [DecidableEq Job] := @Prosa.Validation.PriorityInversionInterface.cumulPriorityInversionCondProjection (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_WorkBearingReadiness_work_bearing_readiness (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.WorkBearingReadiness.work_bearing_readiness (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Schedule_WorkConserving_work_conserving (Job : JobType) [DecidableEq Job] := @Prosa.Model.Schedule.WorkConserving.work_conserving (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_ServiceInversion_BusyPrefix_service_inversion_of_job_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.ServiceInversion.BusyPrefix.service_inversion_of_job_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_ServiceInversion_BusyPrefix_service_inversion_is_bounded_by (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.ServiceInversion.BusyPrefix.service_inversion_is_bounded_by (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_Interference_hp_task_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.Interference.hp_task_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_Interference_hep_job_from_other_ep_task_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.Interference.hep_job_from_other_ep_task_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_Interference_hep_job_from_hp_task_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.Interference.hep_job_from_hp_task_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_Interference_cumulative_interference_from_hep_jobs_from_hp_tasks (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.Interference.cumulative_interference_from_hep_jobs_from_hp_tasks (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_Interference_cumulative_interference_from_hep_jobs_from_other_ep_tasks (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.Interference.cumulative_interference_from_hep_jobs_from_other_ep_tasks (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_Interference_another_hep_job_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.Interference.another_hep_job_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_Interference_another_task_hep_job_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.Interference.another_task_hep_job_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_Interference_another_hep_job_of_same_task_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.Interference.another_hep_job_of_same_task_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_Interference_cumulative_another_hep_job_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.Interference.cumulative_another_hep_job_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Analysis_Definitions_Interference_cumulative_another_task_hep_job_interference (Job : JobType) [DecidableEq Job] := @Prosa.Analysis.Definitions.Interference.cumulative_another_task_hep_job_interference (Job := Job) (PState := processor_state Job)
noncomputable def w_Model_Processor_PlatformProperties_fully_consuming_proc_model (Job : JobType) [DecidableEq Job] := @Prosa.Model.Processor.PlatformProperties.fully_consuming_proc_model (Job := Job) (PState := processor_state Job)
noncomputable def w_Behavior_Schedule_schedule (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Schedule.schedule (Job := Job) (PState := processor_state Job)
noncomputable def w_ProcessorState_Core (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Schedule.ProcessorState.Core Job _ (processor_state Job)
noncomputable def w_ProcessorState_State (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Schedule.ProcessorState.State Job _ (processor_state Job)
noncomputable def w_ProcessorState_coreDecidableEq (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Schedule.ProcessorState.coreDecidableEq Job _ (processor_state Job)
noncomputable def w_ProcessorState_scheduled_in (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Schedule.ProcessorState.scheduled_in Job _ (processor_state Job)
noncomputable def w_ProcessorState_scheduled_on (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Schedule.ProcessorState.scheduled_on Job _ (processor_state Job)
noncomputable def w_ProcessorState_service_in (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Schedule.ProcessorState.service_in Job _ (processor_state Job)
noncomputable def w_ProcessorState_service_on (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Schedule.ProcessorState.service_on Job _ (processor_state Job)
noncomputable def w_ProcessorState_supply_in (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Schedule.ProcessorState.supply_in Job _ (processor_state Job)
noncomputable def w_ProcessorState_supply_on (Job : JobType) [DecidableEq Job] := @Prosa.Behavior.Schedule.ProcessorState.supply_on Job _ (processor_state Job)
noncomputable def w_JobReady_job_ready (Job : JobType) [DecidableEq Job] [Prosa.Behavior.Job.JobCost Job] [Prosa.Behavior.Job.JobArrival Job]
    (jr : Prosa.Behavior.Ready.JobReady Job (processor_state Job)) := jr.job_ready

end Prosa.Validation.IdealInstWitness
