(* Classic validation base (generated by scripts/classic_base.py from the accepted
   certificates/classic_util_tactics/ClassicTacticsCorrespondence.v, re-bound to this export).
   Features: bool decide boolrel andb orb notb decle declt sub min max eqnat booltonat eqtype logic or forall exists *)
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat.
From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedClassicUSPeriodicArrivals.
From FoundationCertificates Require Import PropSPropFoundation LogicalRelation
  SubadditivityNatCorrespondence.



Module I := ImportedClassicUSPeriodicArrivals.

Definition ct_b2l (b : bool) : I.Bool := if b then I.Bool_true else I.Bool_false.
Definition ct_l2b (b : I.Bool) : bool := match b with I.Bool_true => true | I.Bool_false => false end.
Definition CtBoolRel (bR : bool) (bL : I.Bool) : SProp := Lean.eq (ct_b2l bR) bL.

Lemma ct_bool_canonical b : CtBoolRel b (ct_b2l b).
Proof. exact (@Lean.eq_refl _ _). Qed.

Lemma ct_bool_surjective b : CtBoolRel (ct_l2b b) b.
Proof. destruct b; exact (@Lean.eq_refl _ _). Qed.

Lemma ct_bool_rel_logic bR bL : CtBoolRel bR bL -> Logic.eq bL (ct_b2l bR).
Proof. intro H. exact (Logic.eq_sym (imported_eq_to_coq_eq _ _ H)). Qed.

Definition ct_false_elim (Q : SProp) (H : I.False) : Q := match H return Q with end.
Definition ct_coq_false_to_target (H : Logic.False) : I.False := match H return I.False with end.
Definition ct_target_false_to_strict (H : I.False) : StrictlyInhabited Logic.False := match H with end.

Lemma ct_decide_bool (b : bool) (Q : SProp) (d : I.Decidable Q) :
  PropSPropRel (is_true b) Q -> CtBoolRel b (I.Decidable_decide Q d).
Proof.
  intro Hrel. unfold CtBoolRel.
  destruct d as [Hfalse | Htrue]; destruct b; cbn.
  - exact (ct_false_elim _ (Hfalse (prop_to_sprop _ _ Hrel (Logic.eq_refl true)))).
  - exact (@Lean.eq_refl _ _).
  - exact (@Lean.eq_refl _ _).
  - exact (ct_false_elim _ (ct_coq_false_to_target (match sprop_to_prop _ _ Hrel Htrue with end))).
Qed.

Lemma ct_bool_eq aR aL bR bL :
  CtBoolRel aR aL -> CtBoolRel bR bL -> PropSPropRel (Logic.eq aR bR) (Lean.eq aL bL).
Proof.
  intros Ha Hb. rewrite (ct_bool_rel_logic _ _ Ha) (ct_bool_rel_logic _ _ Hb). clear Ha Hb.
  apply prop_sprop_rel_intro.
  - intro E. rewrite E. exact (@Lean.eq_refl _ _).
  - intro E. apply strictly_inhabits. have E' := imported_eq_to_coq_eq _ _ E. clear E.
    move: E'. by case: aR; case: bR.
Qed.

Lemma ct_bool_truth bR bL : CtBoolRel bR bL -> PropSPropRel (is_true bR) (Lean.eq bL I.Bool_true).
Proof. intro H. exact (ct_bool_eq _ _ true I.Bool_true H (@Lean.eq_refl _ _)). Qed.

Lemma ct_bool_false bR bL : CtBoolRel bR bL -> PropSPropRel (Logic.eq bR false) (Lean.eq bL I.Bool_false).
Proof. intro H. exact (ct_bool_eq _ _ false I.Bool_false H (@Lean.eq_refl _ _)). Qed.

Lemma ct_decide_le aR aL bR bL : SubNatRel aR aL -> SubNatRel bR bL ->
  CtBoolRel (leq aR bR) (I.Decidable_decide (I.LE_le_inst1 Lean.Nat I.instLENat aL bL) (I.Nat_decLe aL bL)).
Proof. intros Ha Hb. exact (ct_decide_bool _ _ _ (sub_nat_le_correspondence _ _ _ _ Ha Hb)). Qed.

Lemma ct_decide_lt aR aL bR bL : SubNatRel aR aL -> SubNatRel bR bL ->
  CtBoolRel (ltn aR bR) (I.Decidable_decide (I.LT_lt_inst1 Lean.Nat I.instLTNat aL bL) (I.Nat_decLt aL bL)).
Proof. intros Ha Hb. exact (ct_decide_bool _ _ _ (sub_nat_lt_correspondence _ _ _ _ Ha Hb)). Qed.

Definition ct_sub (a b : Lean.Nat) : Lean.Nat :=
  I.HSub_hSub_inst7 Lean.Nat Lean.Nat Lean.Nat (I.instHSub_inst1 Lean.Nat I.instSubNat) a b.

Lemma ct_sub_canonical (a b : nat) :
  Logic.eq (ct_sub (sub_nat_to_imported a) (sub_nat_to_imported b)) (sub_nat_to_imported (a - b)).
Proof.
  elim: b => [|b IH]; first by rewrite subn0.
  change (Logic.eq (I.Nat_pred (ct_sub (sub_nat_to_imported a) (sub_nat_to_imported b)))
                   (sub_nat_to_imported (a - b.+1))).
  rewrite IH subnS. case: (a - b) => [|k]; reflexivity.
Qed.

Lemma ct_sub_rel aR aL bR bL : SubNatRel aR aL -> SubNatRel bR bL -> SubNatRel (aR - bR) (ct_sub aL bL).
Proof.
  intros Ha Hb. rewrite -(imported_eq_to_coq_eq _ _ Ha) -(imported_eq_to_coq_eq _ _ Hb).
  apply: coq_eq_to_imported_eq. exact (Logic.eq_sym (ct_sub_canonical aR bR)).
Qed.

Lemma ct_eqb_nat aR aL bR bL : SubNatRel aR aL -> SubNatRel bR bL ->
  PropSPropRel (is_true (aR == bR)) (Lean.eq aL bL).
Proof.
  intros Ha Hb. have E := sub_nat_eq_correspondence _ _ _ _ Ha Hb. apply prop_sprop_rel_intro.
  - move=> /eqP H. exact (prop_to_sprop _ _ E H).
  - intro H. apply strictly_inhabits. apply/eqP. exact (sprop_to_prop _ _ E H).
Qed.

Lemma ct_decide_eq_nat aR aL bR bL : SubNatRel aR aL -> SubNatRel bR bL ->
  CtBoolRel (aR == bR) (I.Decidable_decide (Lean.eq aL bL) (I.instDecidableEqNat aL bL)).
Proof. intros Ha Hb. exact (ct_decide_bool _ _ _ (ct_eqb_nat _ _ _ _ Ha Hb)). Qed.

Definition ct_decidable_eq (T : eqType) : I.DecidableEq T :=
  fun x y =>
    match @eqP T x y with
    | ReflectT H => I.Decidable_isTrue (Lean.eq x y) (coq_eq_to_imported_eq x y H)
    | ReflectF H => I.Decidable_isFalse (Lean.eq x y)
        (fun HL => ct_coq_false_to_target (H (imported_eq_to_coq_eq x y HL)))
    end.

Lemma ct_eq_rel (T : Type) (x y : T) : PropSPropRel (Logic.eq x y) (Lean.eq x y).
Proof.
  apply prop_sprop_rel_intro.
  - exact (coq_eq_to_imported_eq x y).
  - intro H. exact (strictly_inhabits (imported_eq_to_coq_eq x y H)).
Qed.

Lemma ct_eqb_rel (T : eqType) (x y : T) : PropSPropRel (is_true (x == y)) (Lean.eq x y).
Proof.
  apply prop_sprop_rel_intro.
  - move=> /eqP. exact (coq_eq_to_imported_eq x y).
  - intro H. apply strictly_inhabits. apply/eqP. exact (imported_eq_to_coq_eq x y H).
Qed.

Lemma ct_decide_eq (T : eqType) (x y : T) :
  CtBoolRel (x == y) (I.Decidable_decide (Lean.eq x y) (ct_decidable_eq T x y)).
Proof. exact (ct_decide_bool _ _ _ (ct_eqb_rel T x y)). Qed.

Lemma ct_imp (P Q : Prop) (PL QL : SProp) :
  PropSPropRel P PL -> PropSPropRel Q QL -> PropSPropRel (P -> Q) (PL -> QL).
Proof.
  intros HP HQ. apply prop_sprop_rel_intro.
  - intros H p. apply (prop_to_sprop _ _ HQ). exact (H (sprop_to_prop _ _ HP p)).
  - intro H. apply strictly_inhabits. intro p.
    apply (sprop_to_prop _ _ HQ). exact (H (prop_to_sprop _ _ HP p)).
Qed.

Lemma ct_and (P Q : Prop) (PL QL : SProp) :
  PropSPropRel P PL -> PropSPropRel Q QL -> PropSPropRel (P /\ Q) (And PL QL).
Proof.
  intros HP HQ. apply prop_sprop_rel_intro.
  - intros [p q]. exact (And_intro PL QL (prop_to_sprop _ _ HP p) (prop_to_sprop _ _ HQ q)).
  - intros [p q]. apply strictly_inhabits. split.
    + exact (sprop_to_prop _ _ HP p).
    + exact (sprop_to_prop _ _ HQ q).
Qed.

Lemma ct_or (P Q : Prop) (PL QL : SProp) :
  PropSPropRel P PL -> PropSPropRel Q QL -> PropSPropRel (P \/ Q) (Or PL QL).
Proof.
  intros HP HQ. apply prop_sprop_rel_intro.
  - intros [p|q]; [exact (Or_inl PL QL (prop_to_sprop _ _ HP p)) | exact (Or_inr PL QL (prop_to_sprop _ _ HQ q))].
  - intros [p|q]; apply strictly_inhabits; [left; exact (sprop_to_prop _ _ HP p) | right; exact (sprop_to_prop _ _ HQ q)].
Qed.

Lemma ct_forall_identity (A : Type) (PR : A -> Prop) (PL : A -> SProp) :
  (forall x, PropSPropRel (PR x) (PL x)) -> PropSPropRel (forall x, PR x) (forall x, PL x).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros HR x. exact (prop_to_sprop _ _ (H x) (HR x)).
  - intro HL. apply strictly_inhabits. intro x. exact (sprop_to_prop _ _ (H x) (HL x)).
Qed.

Lemma ct_forall_bool (PR : bool -> Prop) (PL : I.Bool -> SProp) :
  (forall bR bL, CtBoolRel bR bL -> PropSPropRel (PR bR) (PL bL)) ->
  PropSPropRel (forall b, PR b) (forall b, PL b).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros HR bL. exact (prop_to_sprop _ _ (H _ _ (ct_bool_surjective bL)) (HR _)).
  - intro HL. apply strictly_inhabits. intro bR. exact (sprop_to_prop _ _ (H _ _ (ct_bool_canonical bR)) (HL _)).
Qed.

Lemma ct_forall_nat (PR : nat -> Prop) (PL : Lean.Nat -> SProp) :
  (forall nR nL, SubNatRel nR nL -> PropSPropRel (PR nR) (PL nL)) ->
  PropSPropRel (forall n, PR n) (forall n, PL n).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros HR nL. exact (prop_to_sprop _ _ (H _ _ (sub_nat_rel_surjective nL)) (HR _)).
  - intro HL. apply strictly_inhabits. intro nR. exact (sprop_to_prop _ _ (H _ _ (sub_nat_rel_canonical nR)) (HL _)).
Qed.

Lemma ct_exists_nat (PR : nat -> Prop) (PL : Lean.Nat -> SProp) :
  (forall nR nL, SubNatRel nR nL -> PropSPropRel (PR nR) (PL nL)) ->
  PropSPropRel (exists nR, PR nR) (I.Exists Lean.Nat PL).
Proof.
  intro HP. apply prop_sprop_rel_intro.
  - intros [nR Hn]. exact (I.Exists_intro Lean.Nat PL (sub_nat_to_imported nR)
      (prop_to_sprop _ _ (HP nR (sub_nat_to_imported nR) (sub_nat_rel_canonical nR)) Hn)).
  - intros [nL Hn]. apply strictly_inhabits. exists (sub_nat_to_rocq nL).
    exact (sprop_to_prop _ _ (HP (sub_nat_to_rocq nL) nL (sub_nat_rel_surjective nL)) Hn).
Qed.

Lemma ct_exists_identity (T : Type) (PR : T -> Prop) (PL : T -> SProp) :
  (forall x, PropSPropRel (PR x) (PL x)) -> PropSPropRel (exists x, PR x) (I.Exists T PL).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros [x Hx]. exact (I.Exists_intro T PL x (prop_to_sprop _ _ (H x) Hx)).
  - intros [x Hx]. apply strictly_inhabits. exists x. exact (sprop_to_prop _ _ (H x) Hx).
Qed.


