From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedLcmseq.

Check ImportedLcmseq.Prosa_Util_Lcmseq_lcml.
Check ImportedLcmseq.Prosa_Util_Lcmseq_int_divides_lcm_in_seq.
Check ImportedLcmseq.Prosa_Util_Lcmseq_lcm_seq_divides_lcm_super.
Check ImportedLcmseq.Prosa_Util_Lcmseq_lcm_seq_is_mult_of_all_ints.
Check ImportedLcmseq.Prosa_Util_Lcmseq_all_pos_implies_lcml_pos.

Check ImportedLcmseq.Prosa_Validation_LcmseqInterface_lcmlProjection.
Check ImportedLcmseq.Prosa_Validation_LcmseqInterface_production_gcd_def.
Check ImportedLcmseq.Prosa_Validation_LcmseqInterface_production_lcm_eq_mul_div.
Check ImportedLcmseq.Prosa_Validation_DivModInterface_production_div_add_mod.
Check ImportedLcmseq.Prosa_Validation_DivModInterface_production_mod_lt.
Check ImportedLcmseq.Prosa_Validation_DivModInterface_production_div_zero.
Check ImportedLcmseq.Prosa_Validation_DivModInterface_production_mod_zero.
Check ImportedLcmseq.Prosa_Validation_DivModInterface_production_dvd_iff_mod_eq_zero.

Check ImportedLcmseq.Nat_gcd.
Check ImportedLcmseq.Nat_lcm.
Check ImportedLcmseq.List_foldr.

Print Assumptions ImportedLcmseq.Prosa_Validation_LcmseqInterface_production_gcd_def.
Print Assumptions ImportedLcmseq.Prosa_Validation_LcmseqInterface_production_lcm_eq_mul_div.
Print Assumptions ImportedLcmseq.Prosa_Validation_DivModInterface_production_div_add_mod.
Print Assumptions ImportedLcmseq.Prosa_Validation_DivModInterface_production_mod_lt.
Print Assumptions ImportedLcmseq.Prosa_Validation_DivModInterface_production_div_zero.
Print Assumptions ImportedLcmseq.Prosa_Validation_DivModInterface_production_mod_zero.
Print Assumptions ImportedLcmseq.Prosa_Validation_DivModInterface_production_dvd_iff_mod_eq_zero.
