(* Classic validation list library (generated by scripts/classic_listops.py from the accepted
   certificates/classic_util_list/ClassicListOps.v, re-bound to this export).  Features: core existslist opt size cat mapop filter take nth all mem uniq index *)
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedClassicImplUniSuspSchedule.
From FoundationCertificates Require Import PropSPropFoundation LogicalRelation
  SubadditivityNatCorrespondence ClassicImplUniSuspScheduleBase.



Module I := ImportedClassicImplUniSuspSchedule.

(** Sequences are related to Lean lists through an element conversion [c]
    (the identity for identified carriers, the pair conversion for pairs):
    [ClListRel c sR sL := Lean.eq (cl_map c sR) sL].  Every operation lemma
    relates the MathComp operation on [sR] to the Lean operation on the
    converted list, by structural induction; the Lean side is unfolded one
    constructor at a time by conversion only. *)

Lemma cl_nat_logic nR nL : SubNatRel nR nL -> Logic.eq nL (sub_nat_to_imported nR).
Proof. intro H. exact (Logic.eq_sym (imported_eq_to_coq_eq _ _ H)). Qed.

Lemma cl_nat_input nR nL : SubNatRel nR nL -> Logic.eq (sub_nat_to_rocq nL) nR.
Proof. intro H. rewrite (cl_nat_logic _ _ H). exact (sub_nat_rocq_roundtrip nR). Qed.

Lemma cl_lean_eq (A : Type) (x y : A) : Logic.eq x y -> Lean.eq x y.
Proof. exact (coq_eq_to_imported_eq x y). Qed.

(* ------------------------------------------------------------------ *)
(** * Conversions *)

Fixpoint cl_map {A B : Type} (c : A -> B) (s : seq A) : I.List B :=
  match s with [::] => I.List_nil B | x :: s' => I.List_cons B (c x) (cl_map c s') end.

Fixpoint cl_unmap {A B : Type} (d : B -> A) (l : I.List B) : seq A :=
  match l with I.List_nil => [::] | I.List_cons x l' => d x :: cl_unmap d l' end.

Lemma cl_unmap_map {A B : Type} (c : A -> B) (d : B -> A) (Hdc : forall x, Logic.eq (d (c x)) x) s :
  Logic.eq (cl_unmap d (cl_map c s)) s.
Proof. elim: s => [|x s IH] //=. by rewrite Hdc IH. Qed.

Lemma cl_map_unmap {A B : Type} (c : A -> B) (d : B -> A) (Hcd : forall y, Logic.eq (c (d y)) y) l :
  Logic.eq (cl_map c (cl_unmap d l)) l.
Proof. induction l as [|y l IH]; first reflexivity. cbn. by rewrite Hcd IH. Qed.

Definition ClListRel {A B : Type} (c : A -> B) (sR : seq A) (sL : I.List B) : SProp := Lean.eq (cl_map c sR) sL.

Lemma cl_list_logic {A B} (c : A -> B) sR sL : ClListRel c sR sL -> Logic.eq sL (cl_map c sR).
Proof. intro H. exact (Logic.eq_sym (imported_eq_to_coq_eq _ _ H)). Qed.

Lemma cl_forall_list {A B : Type} (c : A -> B) (d : B -> A) (Hcd : forall y, Logic.eq (c (d y)) y)
    (PR : seq A -> Prop) (PL : I.List B -> SProp) :
  (forall sR sL, ClListRel c sR sL -> PropSPropRel (PR sR) (PL sL)) ->
  PropSPropRel (forall s, PR s) (forall s, PL s).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros HR sL.
    exact (prop_to_sprop _ _ (H _ _ (cl_lean_eq _ _ _ (cl_map_unmap c d Hcd sL))) (HR _)).
  - intro HL. apply strictly_inhabits. intro sR.
    exact (sprop_to_prop _ _ (H sR (cl_map c sR) (@Lean.eq_refl _ _)) (HL _)).
Qed.

Lemma cl_exists_list {A B : Type} (c : A -> B) (d : B -> A) (Hcd : forall y, Logic.eq (c (d y)) y)
    (PR : seq A -> Prop) (PL : I.List B -> SProp) :
  (forall sR sL, ClListRel c sR sL -> PropSPropRel (PR sR) (PL sL)) ->
  PropSPropRel (exists s, PR s) (I.Exists (I.List B) PL).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros [sR HsR]. exact (I.Exists_intro _ PL (cl_map c sR) (prop_to_sprop _ _ (H _ _ (@Lean.eq_refl _ _)) HsR)).
  - intros [sL HsL]. apply strictly_inhabits. exists (cl_unmap d sL).
    exact (sprop_to_prop _ _ (H _ _ (cl_lean_eq _ _ _ (cl_map_unmap c d Hcd sL))) HsL).
Qed.

Definition cl_opt {A : Type} (o : option A) : I.Option A :=
  if o is Some x then I.Option_some A x else I.Option_none A.
Definition cl_unopt {A : Type} (o : I.Option A) : option A :=
  match o with I.Option_some x => Some x | I.Option_none => None end.
Lemma cl_unopt_opt {A} (o : option A) : Logic.eq (cl_unopt (cl_opt o)) o. Proof. by case: o. Qed.
Lemma cl_opt_unopt {A} (o : I.Option A) : Logic.eq (cl_opt (cl_unopt o)) o. Proof. by case: o. Qed.

Lemma cl_size {A B} (c : A -> B) s : SubNatRel (size s) (I.List_length B (cl_map c s)).
Proof. apply: cl_lean_eq. elim: s => [|x s IH] //=. by rewrite IH. Qed.

Lemma cl_map_op {A B A' B'} (c : A -> B) (c' : A' -> B') (fR : A -> A') (fL : B -> B')
    (Hf : forall x, Logic.eq (fL (c x)) (c' (fR x))) s :
  Logic.eq (cl_map c' (map fR s)) (I.List_map B B' fL (cl_map c s)).
Proof. elim: s => [|x s IH] //=. rewrite IH -Hf. reflexivity. Qed.

Lemma cl_filter {A B} (c : A -> B) (pR : A -> bool) (pL : B -> I.Bool)
    (Hp : forall x, CtBoolRel (pR x) (pL (c x))) s :
  Logic.eq (cl_map c (filter pR s)) (I.List_filter B pL (cl_map c s)).
Proof.
  elim: s => [|x s IH] //=.
  have -> : Logic.eq (I.List_filter B pL (I.List_cons B (c x) (cl_map c s)))
      (match pL (c x) with
       | I.Bool_true => I.List_cons B (c x) (I.List_filter B pL (cl_map c s))
       | I.Bool_false => I.List_filter B pL (cl_map c s) end).
  { cbn. destruct (pL (c x)); reflexivity. }
  rewrite (ct_bool_rel_logic _ _ (Hp x)) -IH. by case: (pR x).
Qed.

(* ------------------------------------------------------------------ *)
(** * Membership, uniqueness, index (eqTypes) *)

Section Eq.
Variables (A : eqType) (B : Type) (c : A -> B) (d : B -> A).
Hypothesis Hdc : forall x, Logic.eq (d (c x)) x.
Hypothesis Hcd : forall y, Logic.eq (c (d y)) y.

Lemma cl_c_inj x y : Logic.eq (c x) (c y) -> Logic.eq x y.
Proof. move=> E. by rewrite -(Hdc x) -(Hdc y) E. Qed.

Definition cl_false_elim_s (Q : SProp) (H : is_true false) : Q :=
  match (Bool.diff_false_true H) return Q with end.

Fixpoint cl_mem_forward (x : A) (s : seq A) {struct s} : x \in s -> I.List_Mem B (c x) (cl_map c s) :=
  match s as s0 return x \in s0 -> I.List_Mem B (c x) (cl_map c s0) with
  | [::] => fun H => cl_false_elim_s _ H
  | y :: s' =>
      match @eqP A x y in reflect _ b return (b || (x \in s')) -> I.List_Mem B (c x) (I.List_cons B (c y) (cl_map c s')) with
      | ReflectT E => fun _ =>
          match E in Logic.eq _ z return I.List_Mem B (c x) (I.List_cons B (c z) (cl_map c s')) with
          | Logic.eq_refl => I.List_Mem_head B (c x) _
          end
      | ReflectF _ => fun H => I.List_Mem_tail B (c x) (c y) _ (cl_mem_forward x s' H)
      end
  end.

Fixpoint cl_mem_backward (a : B) (l : I.List B) (H : I.List_Mem B a l) : StrictlyInhabited (d a \in cl_unmap d l) :=
  match H with
  | I.List_Mem_head l' => strictly_inhabits (mem_head (d a) (cl_unmap d l'))
  | I.List_Mem_tail y l' Ht =>
      match cl_mem_backward a l' Ht with
      | strictly_inhabits Hm => strictly_inhabits (introT orP (or_intror Hm) : d a \in d y :: cl_unmap d l')
      end
  end.

Lemma cl_mem_rel x s : PropSPropRel (x \in s) (I.List_Mem B (c x) (cl_map c s)).
Proof.
  apply prop_sprop_rel_intro; first exact (cl_mem_forward x s).
  intro H. have S := cl_mem_backward _ _ H. rewrite Hdc (cl_unmap_map c d Hdc) in S. exact S.
Qed.

Lemma cl_mem_rel_list x s sL : ClListRel c s sL -> PropSPropRel (x \in s) (I.List_Mem B (c x) sL).
Proof. intro H. destruct H. exact (cl_mem_rel x s). Qed.

Lemma cl_notin_rel x s sL : ClListRel c s sL ->
  PropSPropRel (is_true (x \notin s)) (I.Not (I.List_Mem B (c x) sL)).
Proof.
  intro H. have M := cl_mem_rel_list x s sL H. apply prop_sprop_rel_intro.
  - move=> /negP N HL. exact (ct_coq_false_to_target (N (sprop_to_prop _ _ M HL))).
  - intro N. apply strictly_inhabits. apply/negP => Hm.
    exact (interpret_strict _ (ct_target_false_to_strict (N (prop_to_sprop _ _ M Hm)))).
Qed.

End Eq.

Section EqU.
Variables (A : eqType) (B : Type) (c : A -> B) (d : B -> A).
Hypothesis Hdc : forall x, Logic.eq (d (c x)) x.
Hypothesis Hcd : forall y, Logic.eq (c (d y)) y.

End EqU.
