From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedService.

Set Printing All.

Check ImportedService.Prosa_Behavior_Job_work.
Print ImportedService.Prosa_Behavior_Job_work.

Check ImportedService.Prosa_Behavior_Service_scheduled_at.
Print ImportedService.Prosa_Behavior_Service_scheduled_at.

Check ImportedService.Prosa_Behavior_Service_service_at.
Print ImportedService.Prosa_Behavior_Service_service_at.

Check ImportedService.Prosa_Behavior_Service_service_during.
Print ImportedService.Prosa_Behavior_Service_service_during.

Check ImportedService.Prosa_Behavior_Service_service.
Print ImportedService.Prosa_Behavior_Service_service.

Check ImportedService.Prosa_Behavior_Service_completed_by.
Print ImportedService.Prosa_Behavior_Service_completed_by.

Check ImportedService.Prosa_Behavior_Service_completes_at.
Print ImportedService.Prosa_Behavior_Service_completes_at.
