(* Classic validation ordinal library (generated by scripts/classic_ordops.py from the accepted
   classic_util_ord_quantifier and classic_util_bigcat certificates, re-bound to this export).
   Features: ord ordcov famlist search searchany srcexists srcforall existsrel forallrel big bigcl bigsum bigcat *)
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq fintype bigop.
From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedClassicTasksetRta.
From FoundationCertificates Require Import PropSPropFoundation LogicalRelation
  SubadditivityNatCorrespondence ClassicTasksetRtaBase ClassicTasksetRtaList.



Module I := ImportedClassicTasksetRta.
Local Open Scope nat_scope.
Notation cid := (fun z => z).

Lemma co_nat_logic nR nL : SubNatRel nR nL -> Logic.eq nL (sub_nat_to_imported nR).
Proof. intro H. exact (Logic.eq_sym (imported_eq_to_coq_eq _ _ H)). Qed.

Lemma co_nat_input nR nL : SubNatRel nR nL -> Logic.eq (sub_nat_to_rocq nL) nR.
Proof. intro H. rewrite (co_nat_logic _ _ H). exact (sub_nat_rocq_roundtrip nR). Qed.

(* ------------------------------------------------------------------ *)
(** * Ordinals *)

Definition CoOrdRel (nR : nat) (nL : Lean.Nat) (oR : 'I_nR) (oL : Fin nL) : SProp :=
  SubNatRel (nat_of_ord oR) (I.Fin_val nL oL).

Definition co_ord_to_fin nR nL (Hn : SubNatRel nR nL) (oR : 'I_nR) : Fin nL :=
  Fin_mk nL (sub_nat_to_imported (nat_of_ord oR))
    (prop_to_sprop _ _ (sub_nat_lt_correspondence (nat_of_ord oR) _ nR nL (sub_nat_rel_canonical _) Hn) (ltn_ord oR)).

Definition co_fin_to_ord nR nL (Hn : SubNatRel nR nL) (oL : Fin nL) : 'I_nR :=
  @Ordinal nR (sub_nat_to_rocq (I.Fin_val nL oL))
    (sprop_to_prop _ _ (sub_nat_lt_correspondence _ (I.Fin_val nL oL) nR nL
       (sub_nat_rel_surjective (I.Fin_val nL oL)) Hn) (I.Fin_isLt nL oL)).

Lemma co_ord_canonical nR nL (Hn : SubNatRel nR nL) oR : CoOrdRel nR nL oR (co_ord_to_fin nR nL Hn oR).
Proof. exact (sub_nat_rel_canonical _). Qed.

Lemma co_ord_surjective nR nL (Hn : SubNatRel nR nL) oL : CoOrdRel nR nL (co_fin_to_ord nR nL Hn oL) oL.
Proof. exact (sub_nat_rel_surjective _). Qed.

Lemma co_ord_eq nR nL oR pR oL : CoOrdRel nR nL oR oL -> CoOrdRel nR nL pR oL -> Logic.eq oR pR.
Proof. intros H1 H2. apply: ord_inj. rewrite -(co_nat_input _ _ H1) -(co_nat_input _ _ H2). reflexivity. Qed.

Lemma co_fin_eq nL (a b : Fin nL) : Logic.eq (I.Fin_val nL a) (I.Fin_val nL b) -> Logic.eq a b.
Proof. destruct a as [va pa], b as [vb pb]. cbn. intro E. destruct E. reflexivity. Qed.

Lemma co_fin_rel_eq nR nL oR oL pL : CoOrdRel nR nL oR oL -> CoOrdRel nR nL oR pL -> Logic.eq oL pL.
Proof.
  intros H1 H2. apply: co_fin_eq.
  rewrite -(imported_eq_to_coq_eq _ _ H1) -(imported_eq_to_coq_eq _ _ H2). reflexivity.
Qed.

Definition CoOrdPredRel nR nL (PR : 'I_nR -> bool) (PL : Fin nL -> I.Bool) : SProp :=
  forall oR oL, CoOrdRel nR nL oR oL -> CtBoolRel (PR oR) (PL oL).

Lemma co_forall_cover_sprop (A B : Type) (Rel : A -> B -> SProp) (toB : A -> B) (toA : B -> A)
    (HtoB : forall a, Rel a (toB a)) (HtoA : forall b, Rel (toA b) b) (PR : A -> Prop) (PL : B -> SProp) :
  (forall a b, Rel a b -> PropSPropRel (PR a) (PL b)) -> PropSPropRel (forall a, PR a) (forall b, PL b).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros HR b. exact (prop_to_sprop _ _ (H _ _ (HtoA b)) (HR (toA b))).
  - intro HL. apply strictly_inhabits. intro a. exact (sprop_to_prop _ _ (H _ _ (HtoB a)) (HL (toB a))).
Qed.

Lemma co_forall_ord_pred nR nL (Hn : SubNatRel nR nL) (PR : pred 'I_nR -> Prop) (PL : (Fin nL -> I.Bool) -> SProp) :
  (forall pR pL, CoOrdPredRel nR nL pR pL -> PropSPropRel (PR pR) (PL pL)) ->
  PropSPropRel (forall p, PR p) (forall p, PL p).
Proof.
  apply (co_forall_cover_sprop _ _ (CoOrdPredRel nR nL)
    (fun pR oL => ct_b2l (pR (co_fin_to_ord nR nL Hn oL))) (fun pL oR => ct_l2b (pL (co_ord_to_fin nR nL Hn oR)))).
  - intros pR oR oL Ho. rewrite (co_ord_eq _ _ _ _ _ Ho (co_ord_surjective nR nL Hn oL)). exact (ct_bool_canonical _).
  - intros pL oR oL Ho. rewrite -(co_fin_rel_eq _ _ _ _ _ (co_ord_canonical nR nL Hn oR) Ho). exact (ct_bool_surjective _).
Qed.

Lemma co_forall_ord nR nL (Hn : SubNatRel nR nL) (PR : 'I_nR -> Prop) (PL : Fin nL -> SProp) :
  (forall oR oL, CoOrdRel nR nL oR oL -> PropSPropRel (PR oR) (PL oL)) -> PropSPropRel (forall o, PR o) (forall o, PL o).
Proof.
  exact (co_forall_cover_sprop _ _ (CoOrdRel nR nL) (co_ord_to_fin nR nL Hn) (co_fin_to_ord nR nL Hn)
    (co_ord_canonical nR nL Hn) (co_ord_surjective nR nL Hn) PR PL).
Qed.

Lemma co_exists_ord nR nL (Hn : SubNatRel nR nL) (PR : 'I_nR -> Prop) (PL : Fin nL -> SProp) :
  (forall oR oL, CoOrdRel nR nL oR oL -> PropSPropRel (PR oR) (PL oL)) -> PropSPropRel (exists o, PR o) (I.Exists (Fin nL) PL).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros [o Ho]. exact (I.Exists_intro _ PL _ (prop_to_sprop _ _ (H _ _ (co_ord_canonical nR nL Hn o)) Ho)).
  - intros [oL Ho]. apply strictly_inhabits. exists (co_fin_to_ord nR nL Hn oL).
    exact (sprop_to_prop _ _ (H _ _ (co_ord_surjective nR nL Hn oL)) Ho).
Qed.

Lemma co_ord_eq_rel nR nL o1 o2 l1 l2 : CoOrdRel nR nL o1 l1 -> CoOrdRel nR nL o2 l2 ->
  PropSPropRel (Logic.eq o1 o2) (Lean.eq l1 l2).
Proof.
  intros H1 H2. apply prop_sprop_rel_intro.
  - intros ->. rewrite (co_fin_rel_eq _ _ _ _ _ H1 H2). exact (@Lean.eq_refl _ _).
  - intro E. apply strictly_inhabits. have E' := imported_eq_to_coq_eq _ _ E. subst l2. exact (co_ord_eq _ _ _ _ _ H1 H2).
Qed.

(** Ordinal-indexed families of sequences. *)
Definition CoFamRel nR nL (T : Type) (fR : 'I_nR -> seq T) (fL : Fin nL -> I.List T) : SProp :=
  forall oR oL, CoOrdRel nR nL oR oL -> ClListRel cid (fR oR) (fL oL).

Lemma co_forall_fam nR nL (Hn : SubNatRel nR nL) (T : Type) (PR : ('I_nR -> seq T) -> Prop) (PL : (Fin nL -> I.List T) -> SProp) :
  (forall fR fL, CoFamRel nR nL T fR fL -> PropSPropRel (PR fR) (PL fL)) -> PropSPropRel (forall f, PR f) (forall f, PL f).
Proof.
  have Hcd : forall l : I.List T, Logic.eq (cl_map cid (cl_unmap cid l)) l := cl_map_unmap cid cid (fun _ => Logic.eq_refl _).
  apply (co_forall_cover_sprop _ _ (CoFamRel nR nL T)
    (fun fR oL => cl_map cid (fR (co_fin_to_ord nR nL Hn oL))) (fun fL oR => cl_unmap cid (fL (co_ord_to_fin nR nL Hn oR)))).
  - intros fR oR oL Ho. rewrite (co_ord_eq _ _ _ _ _ Ho (co_ord_surjective nR nL Hn oL)). exact (@Lean.eq_refl _ _).
  - intros fL oR oL Ho. rewrite -(co_fin_rel_eq _ _ _ _ _ (co_ord_canonical nR nL Hn oR) Ho).
    apply: coq_eq_to_imported_eq. exact (Hcd _).
Qed.

Definition co_ord_family (nR : nat) (Q : 'I_nR -> bool) (dflt : bool) (k : nat) : bool :=
  if insub k is Some o then Q o else dflt.

Definition co_target_family (nL : Lean.Nat) (q : Fin nL -> I.Bool) (dflt : I.Bool) (k : Lean.Nat) : I.Bool :=
  I.dite I.Bool (I.LT_lt_inst1 Lean.Nat I.instLTNat k nL) (I.Nat_decLt k nL) (fun h => q (Fin_mk nL k h)) (fun _ => dflt).

Lemma co_family_related (nR : nat) (Q : 'I_nR -> bool) (q : Fin (sub_nat_to_imported nR) -> I.Bool)
    (HQ : CoOrdPredRel nR (sub_nat_to_imported nR) Q q) (dflt : bool) :
  forall kR, Logic.eq (co_target_family (sub_nat_to_imported nR) q (ct_b2l dflt) (sub_nat_to_imported kR))
                      (ct_b2l (co_ord_family nR Q dflt kR)).
Proof.
  intro kR. unfold co_target_family, co_ord_family.
  have Hlt := sub_nat_lt_correspondence kR _ nR _ (sub_nat_rel_canonical kR) (sub_nat_rel_canonical nR).
  destruct (I.Nat_decLt (sub_nat_to_imported kR) (sub_nat_to_imported nR)) as [h|h]; cbn.
  - have Hge : Logic.eq (kR < nR) false.
    { apply/negbTE/negP. move=> Hsrc. exact (interpret_strict _ (ct_target_false_to_strict (h (prop_to_sprop _ _ Hlt Hsrc)))). }
    by rewrite (@insubF _ _ _ kR Hge).
  - have Hsrc : kR < nR := sprop_to_prop _ _ Hlt h.
    rewrite (insubT (fun x => x < nR) Hsrc) /=. apply: ct_bool_rel_logic. apply: HQ. exact (sub_nat_rel_canonical kR).
Qed.

Definition co_one : Lean.Nat := I.OfNat_ofNat_inst1 Lean.Nat 1 (I.instOfNatNat 1).

Lemma co_all_iota (fR : nat -> bool) (fL : Lean.Nat -> I.Bool)
    (Hf : forall kR, Logic.eq (fL (sub_nat_to_imported kR)) (ct_b2l (fR kR))) :
  forall nR sR, Logic.eq
    (I.List_all_inst1 Lean.Nat (I.List_range' (sub_nat_to_imported sR) (sub_nat_to_imported nR) co_one) fL)
    (ct_b2l (all fR (iota sR nR))).
Proof.
  elim => [|n IH] sR; first reflexivity.
  change (Logic.eq (I.Bool_and (fL (sub_nat_to_imported sR))
      (I.List_all_inst1 Lean.Nat (I.List_range' (sub_nat_to_imported (S sR)) (sub_nat_to_imported n) co_one) fL))
    (ct_b2l (fR sR && all fR (iota (S sR) n)))).
  rewrite Hf IH. by case: (fR sR).
Qed.

Lemma co_any_iota (fR : nat -> bool) (fL : Lean.Nat -> I.Bool)
    (Hf : forall kR, Logic.eq (fL (sub_nat_to_imported kR)) (ct_b2l (fR kR))) :
  forall nR sR, Logic.eq
    (I.List_any_inst1 Lean.Nat (I.List_range' (sub_nat_to_imported sR) (sub_nat_to_imported nR) co_one) fL)
    (ct_b2l (has fR (iota sR nR))).
Proof.
  elim => [|n IH] sR; first reflexivity.
  change (Logic.eq (I.Bool_or (fL (sub_nat_to_imported sR))
      (I.List_any_inst1 Lean.Nat (I.List_range' (sub_nat_to_imported (S sR)) (sub_nat_to_imported n) co_one) fL))
    (ct_b2l (fR sR || has fR (iota (S sR) n)))).
  rewrite Hf IH. by case: (fR sR).
Qed.

(** Source rewrites. *)
Lemma co_exists_iota (nR : nat) (Q : 'I_nR -> bool) :
  Logic.eq [exists x in 'I_nR, Q x] (has (co_ord_family nR Q false) (iota 0 nR)).
Proof.
  apply/existsP/hasP.
  - move=> [x /andP [_ Hx]]. exists (nat_of_ord x); first by rewrite mem_iota add0n ltn_ord.
    by rewrite /co_ord_family valK.
  - move=> [k Hk]. rewrite mem_iota add0n in Hk. move/andP: Hk => [_ Hk].
    rewrite /co_ord_family insubT => Hq. by exists (Ordinal Hk).
Qed.

Lemma co_forall_iota (nR : nat) (Q : 'I_nR -> bool) :
  Logic.eq [forall x in 'I_nR, Q x] (all (co_ord_family nR Q true) (iota 0 nR)).
Proof.
  apply/forallP/allP.
  - move=> H k. rewrite mem_iota add0n => /andP [_ Hk]. rewrite /co_ord_family insubT. exact: (implyP (H _)).
  - move=> H x. apply/implyP => _. have := H (nat_of_ord x). rewrite mem_iota add0n ltn_ord /co_ord_family valK. by apply.
Qed.

Lemma co_exists_rel nR nL (Hn : SubNatRel nR nL) Q q (HQ : CoOrdPredRel nR nL Q q) :
  CtBoolRel [exists x in 'I_nR, Q x] (I.List_any_inst1 (Fin nL) (I.List_finRange nL) q).
Proof.
  have E := co_nat_logic _ _ Hn. subst nL. apply: coq_eq_to_imported_eq. apply: Logic.eq_sym.
  rewrite (imported_eq_to_coq_eq _ _ (I.Prosa_Validation_ClassicTasksetRtaInterface_finRange_any (sub_nat_to_imported nR) q)).
  rewrite co_exists_iota.
  exact (co_any_iota (co_ord_family nR Q false) (co_target_family (sub_nat_to_imported nR) q I.Bool_false)
           (co_family_related nR Q q HQ false) nR O).
Qed.

Lemma co_forall_rel nR nL (Hn : SubNatRel nR nL) Q q (HQ : CoOrdPredRel nR nL Q q) :
  CtBoolRel [forall x in 'I_nR, Q x] (I.List_all_inst1 (Fin nL) (I.List_finRange nL) q).
Proof.
  have E := co_nat_logic _ _ Hn. subst nL. apply: coq_eq_to_imported_eq. apply: Logic.eq_sym.
  rewrite (imported_eq_to_coq_eq _ _ (I.Prosa_Validation_ClassicTasksetRtaInterface_finRange_all (sub_nat_to_imported nR) q)).
  rewrite co_forall_iota.
  exact (co_all_iota (co_ord_family nR Q true) (co_target_family (sub_nat_to_imported nR) q I.Bool_true)
           (co_family_related nR Q q HQ true) nR O).
Qed.

Definition co_fam {nR : nat} {A : Type} (F : 'I_nR -> A) (d : A) (k : nat) : A :=
  if insub k is Some o then F o else d.

Definition co_tfam {nL : Lean.Nat} {B : Type} (F : Fin nL -> B) (d : B) (k : Lean.Nat) : B :=
  I.dite B (I.LT_lt_inst1 Lean.Nat I.instLTNat k nL) (I.Nat_decLt k nL) (fun h => F (Fin_mk nL k h)) (fun _ => d).

Lemma co_fam_related (nR : nat) {A B : Type} (c : A -> B) (FR : 'I_nR -> A) (FL : Fin (sub_nat_to_imported nR) -> B) (dA : A)
    (HF : forall o oL, CoOrdRel nR (sub_nat_to_imported nR) o oL -> Logic.eq (FL oL) (c (FR o))) :
  forall k, Logic.eq (co_tfam FL (c dA) (sub_nat_to_imported k)) (c (co_fam FR dA k)).
Proof.
  intro k. unfold co_tfam, co_fam.
  have Hlt := sub_nat_lt_correspondence k _ nR _ (sub_nat_rel_canonical k) (sub_nat_rel_canonical nR).
  destruct (I.Nat_decLt (sub_nat_to_imported k) (sub_nat_to_imported nR)) as [h|h]; cbn.
  - have Hge : Logic.eq (k < nR) false.
    { apply/negbTE/negP. move=> Hsrc. exact (interpret_strict _ (ct_target_false_to_strict (h (prop_to_sprop _ _ Hlt Hsrc)))). }
    by rewrite (@insubF _ _ _ k Hge).
  - have Hsrc : k < nR := sprop_to_prop _ _ Hlt h.
    rewrite (insubT (fun x => x < nR) Hsrc) /=. apply: HF. exact (sub_nat_rel_canonical k).
Qed.

Lemma co_big_seq_ord {R : Type} (op : R -> R -> R) (idx : R) nR (F : 'I_nR -> R) (d : R) (s : seq 'I_nR) :
  Logic.eq (\big[op/idx]_(i <- s) F i) (foldr op idx (map (co_fam F d) (map (@nat_of_ord nR) s))).
Proof. elim: s => [|o s IH]; first by rewrite big_nil. by rewrite big_cons IH /= /co_fam valK. Qed.

Lemma co_index_enum_vals nR : Logic.eq (map (@nat_of_ord nR) (index_enum 'I_nR)) (iota 0 nR).
Proof.
  rewrite -val_enum_ord -deprecated_filter_index_enum.
  congr map. by apply/esym/all_filterP/allP.
Qed.

Lemma co_big_ord {R : Type} (op : R -> R -> R) (idx : R) nR (F : 'I_nR -> R) (d : R) :
  Logic.eq (\big[op/idx]_(i < nR) F i) (foldr op idx (map (co_fam F d) (iota 0 nR))).
Proof. rewrite -co_index_enum_vals -co_big_seq_ord. by []. Qed.

Fixpoint co_natl (s : seq nat) : I.List_inst1 Lean.Nat :=
  match s with [::] => I.List_nil_inst1 _ | x :: s' => I.List_cons_inst1 _ (sub_nat_to_imported x) (co_natl s') end.

Lemma co_iota_range : forall n s,
  Logic.eq (I.List_range' (sub_nat_to_imported s) (sub_nat_to_imported n) co_one) (co_natl (iota s n)).
Proof.
  elim => [|n IH] s; first reflexivity.
  change (Logic.eq (I.List_cons_inst1 _ (sub_nat_to_imported s)
      (I.List_range' (sub_nat_to_imported (S s)) (sub_nat_to_imported n) co_one))
    (I.List_cons_inst1 _ (sub_nat_to_imported s) (co_natl (iota (S s) n)))).
  by rewrite IH.
Qed.

Lemma co_map_inst1 {B : Type} (f : Lean.Nat -> B) : forall s,
  Logic.eq (I.List_map_inst1 Lean.Nat B f (co_natl s)) (cl_map (fun k => f (sub_nat_to_imported k)) s).
Proof.
  elim => [|k s IH] //=.
  change (Logic.eq (I.List_cons B (f (sub_nat_to_imported k)) (I.List_map_inst1 Lean.Nat B f (co_natl s)))
                   (I.List_cons B (f (sub_nat_to_imported k)) (cl_map (fun k => f (sub_nat_to_imported k)) s))).
  by rewrite IH.
Qed.

Lemma co_cl_map_comp {A B C : Type} (f : A -> B) (g : B -> C) : forall s : seq A,
  Logic.eq (cl_map (fun x => g (f x)) s) (cl_map g (map f s)).
Proof. elim => [|x s IH] //=. by rewrite IH. Qed.

Lemma co_cl_map_ext {A B : Type} (f g : A -> B) (H : forall x, Logic.eq (f x) (g x)) : forall s : seq A,
  Logic.eq (cl_map f s) (cl_map g s).
Proof. elim => [|x s IH] //=. by rewrite H IH. Qed.

Lemma co_foldr_add (f : Lean.Nat -> Lean.Nat) (g : nat -> nat) (Hf : forall k, Logic.eq (f (sub_nat_to_imported k)) (sub_nat_to_imported (g k))) :
  forall s, Logic.eq (I.List_foldr_inst3 Lean.Nat Lean.Nat Lean.Nat_add (I.OfNat_ofNat_inst1 Lean.Nat 0 (I.instOfNatNat 0))
                        (I.List_map_inst3 Lean.Nat Lean.Nat f (co_natl s)))
                     (sub_nat_to_imported (foldr addn 0 (map g s))).
Proof.
  elim => [|k s IH] //=.
  change (Logic.eq (Lean.Nat_add (f (sub_nat_to_imported k))
            (I.List_foldr_inst3 Lean.Nat Lean.Nat Lean.Nat_add (I.OfNat_ofNat_inst1 Lean.Nat 0 (I.instOfNatNat 0))
              (I.List_map_inst3 Lean.Nat Lean.Nat f (co_natl s))))
         (sub_nat_to_imported (g k + foldr addn 0 (map g s)))).
  rewrite IH Hf. exact (imported_eq_to_coq_eq _ _ (sub_add_canonical _ _)).
Qed.


