(* Classic validation list library (generated by scripts/classic_listops.py from the accepted
   certificates/classic_util_list/ClassicListOps.v, re-bound to this export).  Features: core existslist opt size cat mapop filter take nth all mem uniq index *)
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedClassicUniConstruction.
From FoundationCertificates Require Import PropSPropFoundation LogicalRelation
  SubadditivityNatCorrespondence ClassicUniConstructionBase.



Module I := ImportedClassicUniConstruction.

(** Sequences are related to Lean lists through an element conversion [c]
    (the identity for identified carriers, the pair conversion for pairs):
    [ClListRel c sR sL := Lean.eq (cl_map c sR) sL].  Every operation lemma
    relates the MathComp operation on [sR] to the Lean operation on the
    converted list, by structural induction; the Lean side is unfolded one
    constructor at a time by conversion only. *)

Lemma cl_nat_logic nR nL : SubNatRel nR nL -> Logic.eq nL (sub_nat_to_imported nR).
Proof. intro H. exact (Logic.eq_sym (imported_eq_to_coq_eq _ _ H)). Qed.

Lemma cl_nat_input nR nL : SubNatRel nR nL -> Logic.eq (sub_nat_to_rocq nL) nR.
Proof. intro H. rewrite (cl_nat_logic _ _ H). exact (sub_nat_rocq_roundtrip nR). Qed.

Lemma cl_lean_eq (A : Type) (x y : A) : Logic.eq x y -> Lean.eq x y.
Proof. exact (coq_eq_to_imported_eq x y). Qed.

(* ------------------------------------------------------------------ *)
(** * Conversions *)

Fixpoint cl_map {A B : Type} (c : A -> B) (s : seq A) : I.List B :=
  match s with [::] => I.List_nil B | x :: s' => I.List_cons B (c x) (cl_map c s') end.

Fixpoint cl_unmap {A B : Type} (d : B -> A) (l : I.List B) : seq A :=
  match l with I.List_nil => [::] | I.List_cons x l' => d x :: cl_unmap d l' end.

Lemma cl_unmap_map {A B : Type} (c : A -> B) (d : B -> A) (Hdc : forall x, Logic.eq (d (c x)) x) s :
  Logic.eq (cl_unmap d (cl_map c s)) s.
Proof. elim: s => [|x s IH] //=. by rewrite Hdc IH. Qed.

Lemma cl_map_unmap {A B : Type} (c : A -> B) (d : B -> A) (Hcd : forall y, Logic.eq (c (d y)) y) l :
  Logic.eq (cl_map c (cl_unmap d l)) l.
Proof. induction l as [|y l IH]; first reflexivity. cbn. by rewrite Hcd IH. Qed.

Definition ClListRel {A B : Type} (c : A -> B) (sR : seq A) (sL : I.List B) : SProp := Lean.eq (cl_map c sR) sL.

Lemma cl_list_logic {A B} (c : A -> B) sR sL : ClListRel c sR sL -> Logic.eq sL (cl_map c sR).
Proof. intro H. exact (Logic.eq_sym (imported_eq_to_coq_eq _ _ H)). Qed.

Lemma cl_forall_list {A B : Type} (c : A -> B) (d : B -> A) (Hcd : forall y, Logic.eq (c (d y)) y)
    (PR : seq A -> Prop) (PL : I.List B -> SProp) :
  (forall sR sL, ClListRel c sR sL -> PropSPropRel (PR sR) (PL sL)) ->
  PropSPropRel (forall s, PR s) (forall s, PL s).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros HR sL.
    exact (prop_to_sprop _ _ (H _ _ (cl_lean_eq _ _ _ (cl_map_unmap c d Hcd sL))) (HR _)).
  - intro HL. apply strictly_inhabits. intro sR.
    exact (sprop_to_prop _ _ (H sR (cl_map c sR) (@Lean.eq_refl _ _)) (HL _)).
Qed.

Definition cl_opt {A : Type} (o : option A) : I.Option A :=
  if o is Some x then I.Option_some A x else I.Option_none A.
Definition cl_unopt {A : Type} (o : I.Option A) : option A :=
  match o with I.Option_some x => Some x | I.Option_none => None end.
Lemma cl_unopt_opt {A} (o : option A) : Logic.eq (cl_unopt (cl_opt o)) o. Proof. by case: o. Qed.
Lemma cl_opt_unopt {A} (o : I.Option A) : Logic.eq (cl_opt (cl_unopt o)) o. Proof. by case: o. Qed.

Lemma cl_map_op {A B A' B'} (c : A -> B) (c' : A' -> B') (fR : A -> A') (fL : B -> B')
    (Hf : forall x, Logic.eq (fL (c x)) (c' (fR x))) s :
  Logic.eq (cl_map c' (map fR s)) (I.List_map B B' fL (cl_map c s)).
Proof. elim: s => [|x s IH] //=. rewrite IH -Hf. reflexivity. Qed.

(* ------------------------------------------------------------------ *)
(** * Membership, uniqueness, index (eqTypes) *)

Section Eq.
Variables (A : eqType) (B : Type) (c : A -> B) (d : B -> A).
Hypothesis Hdc : forall x, Logic.eq (d (c x)) x.
Hypothesis Hcd : forall y, Logic.eq (c (d y)) y.

Lemma cl_c_inj x y : Logic.eq (c x) (c y) -> Logic.eq x y.
Proof. move=> E. by rewrite -(Hdc x) -(Hdc y) E. Qed.

Definition cl_false_elim_s (Q : SProp) (H : is_true false) : Q :=
  match (Bool.diff_false_true H) return Q with end.

End Eq.

Section EqU.
Variables (A : eqType) (B : Type) (c : A -> B) (d : B -> A).
Hypothesis Hdc : forall x, Logic.eq (d (c x)) x.
Hypothesis Hcd : forall y, Logic.eq (c (d y)) y.

End EqU.
