(* Classic validation ordinal library (generated by scripts/classic_ordops.py from the accepted
   classic_util_ord_quantifier and classic_util_bigcat certificates, re-bound to this export).
   Features: ord *)
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq fintype bigop.
From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedClassicImplApaTask.
From FoundationCertificates Require Import PropSPropFoundation LogicalRelation
  SubadditivityNatCorrespondence ClassicImplApaTaskBase ClassicImplApaTaskList1.

Module I := ImportedClassicImplApaTask.
Local Open Scope nat_scope.
Notation cid := (fun z => z).

Lemma co_nat_logic nR nL : SubNatRel nR nL -> Logic.eq nL (sub_nat_to_imported nR).
Proof. intro H. exact (Logic.eq_sym (imported_eq_to_coq_eq _ _ H)). Qed.

Lemma co_nat_input nR nL : SubNatRel nR nL -> Logic.eq (sub_nat_to_rocq nL) nR.
Proof. intro H. rewrite (co_nat_logic _ _ H). exact (sub_nat_rocq_roundtrip nR). Qed.

(* ------------------------------------------------------------------ *)
(** * Ordinals *)

Definition CoOrdRel (nR : nat) (nL : Lean.Nat) (oR : 'I_nR) (oL : Fin nL) : SProp :=
  SubNatRel (nat_of_ord oR) (I.Fin_val nL oL).

Definition co_ord_to_fin nR nL (Hn : SubNatRel nR nL) (oR : 'I_nR) : Fin nL :=
  Fin_mk nL (sub_nat_to_imported (nat_of_ord oR))
    (prop_to_sprop _ _ (sub_nat_lt_correspondence (nat_of_ord oR) _ nR nL (sub_nat_rel_canonical _) Hn) (ltn_ord oR)).

Definition co_fin_to_ord nR nL (Hn : SubNatRel nR nL) (oL : Fin nL) : 'I_nR :=
  @Ordinal nR (sub_nat_to_rocq (I.Fin_val nL oL))
    (sprop_to_prop _ _ (sub_nat_lt_correspondence _ (I.Fin_val nL oL) nR nL
       (sub_nat_rel_surjective (I.Fin_val nL oL)) Hn) (I.Fin_isLt nL oL)).

Lemma co_ord_canonical nR nL (Hn : SubNatRel nR nL) oR : CoOrdRel nR nL oR (co_ord_to_fin nR nL Hn oR).
Proof. exact (sub_nat_rel_canonical _). Qed.

Lemma co_ord_surjective nR nL (Hn : SubNatRel nR nL) oL : CoOrdRel nR nL (co_fin_to_ord nR nL Hn oL) oL.
Proof. exact (sub_nat_rel_surjective _). Qed.

Lemma co_ord_eq nR nL oR pR oL : CoOrdRel nR nL oR oL -> CoOrdRel nR nL pR oL -> Logic.eq oR pR.
Proof. intros H1 H2. apply: ord_inj. rewrite -(co_nat_input _ _ H1) -(co_nat_input _ _ H2). reflexivity. Qed.

Lemma co_fin_eq nL (a b : Fin nL) : Logic.eq (I.Fin_val nL a) (I.Fin_val nL b) -> Logic.eq a b.
Proof. destruct a as [va pa], b as [vb pb]. cbn. intro E. destruct E. reflexivity. Qed.

Lemma co_fin_rel_eq nR nL oR oL pL : CoOrdRel nR nL oR oL -> CoOrdRel nR nL oR pL -> Logic.eq oL pL.
Proof.
  intros H1 H2. apply: co_fin_eq.
  rewrite -(imported_eq_to_coq_eq _ _ H1) -(imported_eq_to_coq_eq _ _ H2). reflexivity.
Qed.

Definition CoOrdPredRel nR nL (PR : 'I_nR -> bool) (PL : Fin nL -> I.Bool) : SProp :=
  forall oR oL, CoOrdRel nR nL oR oL -> CtBoolRel (PR oR) (PL oL).

Lemma co_forall_cover_sprop (A B : Type) (Rel : A -> B -> SProp) (toB : A -> B) (toA : B -> A)
    (HtoB : forall a, Rel a (toB a)) (HtoA : forall b, Rel (toA b) b) (PR : A -> Prop) (PL : B -> SProp) :
  (forall a b, Rel a b -> PropSPropRel (PR a) (PL b)) -> PropSPropRel (forall a, PR a) (forall b, PL b).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros HR b. exact (prop_to_sprop _ _ (H _ _ (HtoA b)) (HR (toA b))).
  - intro HL. apply strictly_inhabits. intro a. exact (sprop_to_prop _ _ (H _ _ (HtoB a)) (HL (toB a))).
Qed.

Lemma co_forall_ord_pred nR nL (Hn : SubNatRel nR nL) (PR : pred 'I_nR -> Prop) (PL : (Fin nL -> I.Bool) -> SProp) :
  (forall pR pL, CoOrdPredRel nR nL pR pL -> PropSPropRel (PR pR) (PL pL)) ->
  PropSPropRel (forall p, PR p) (forall p, PL p).
Proof.
  apply (co_forall_cover_sprop _ _ (CoOrdPredRel nR nL)
    (fun pR oL => ct_b2l (pR (co_fin_to_ord nR nL Hn oL))) (fun pL oR => ct_l2b (pL (co_ord_to_fin nR nL Hn oR)))).
  - intros pR oR oL Ho. rewrite (co_ord_eq _ _ _ _ _ Ho (co_ord_surjective nR nL Hn oL)). exact (ct_bool_canonical _).
  - intros pL oR oL Ho. rewrite -(co_fin_rel_eq _ _ _ _ _ (co_ord_canonical nR nL Hn oR) Ho). exact (ct_bool_surjective _).
Qed.

