From FoundationCertificates Require Import
  ArrivalsSeqBaseAdapter ArrivalsSeqOperations ArrivalsSeqCorrespondence ArrivalsCorrespondence WorkloadCorrespondence AbstractDefinitionsBaseAdapter ServiceBaseAdapter ServiceNatBoolOperations AbstractDefinitionsArrivalOperations AbstractDefinitionsClasses AbstractDefinitionsNatBoolOperations AbstractDefinitionsIntervalOperations AbstractDefinitionsOperations AbstractDefinitionsSums AbstractDefinitionsLogical ServiceIntervalOperations ServiceScheduleOperations AbstractDefinitionsPendingOperations AbstractDefinitionsTaskOperations AbstractDefinitionsBusyIntervalHelpers AbstractRtaHelpers JitterSvcBaseAdapter JitterSvcNatBoolOperations JitterSvcIntervalOperations JitterSvcScheduleOperations JitterSvcJobOperations PreemptionParameterCorrespondence TaskPreemptionParametersCorrespondence IdealAbstractRtaHelpers ArrivalSequenceBaseAdapter ArrivalSequenceOperations TaskScheduleCorrespondence CurvesCorrespondence RequestBoundFunctionCorrespondence SequentialityCorrespondence ServiceOfJobsCorrespondence SupplyScheduleBaseAdapter SupplyScheduleFiniteOperations SupplyScheduleOperations SupplyBaseAdapter SupplyNatBoolOperations SupplyIntervalOperations SupplyCorrespondence IbfTaskHelpers IbfSupplyTaskCorrespondence IbfTaskFullHelpers ServiceInversionPredCorrespondence InterferenceCorrespondence RsIwHelpers WorkloadBoundedCorrespondence ServiceInversionBusyPrefixCorrespondence ArrivalSequenceCorrespondence BusyIntervalClassicalHelpers PredHelpers SbfBusyCorrespondence SearchSpaceFifoCorrespondence FifoFixpointCorrespondence.
Set Printing Width 1000.

Goal Logic.True. idtac "AUDIT_BEGIN soln_abstract_response_time_recurrence_correspondence". exact Logic.I. Qed.
Print Assumptions soln_abstract_response_time_recurrence_correspondence.
Goal Logic.True. idtac "AUDIT_END soln_abstract_response_time_recurrence_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ffx_forall_sbf". exact Logic.I. Qed.
Print Assumptions ffx_forall_sbf.
Goal Logic.True. idtac "AUDIT_END ffx_forall_sbf". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ffx_fifo_rel". exact Logic.I. Qed.
Print Assumptions ffx_fifo_rel.
Goal Logic.True. idtac "AUDIT_END ffx_fifo_rel". exact Logic.I. Qed.
