(* Classic validation list library over the universe instance [List_inst1] (mechanical renaming of the
   core/mem/uniq parts: [I.List*] -> [I.List*_inst1], [cl_*] -> [cl1_*], [ClListRel] -> [ClListRel1]); (generated by scripts/classic_listops.py from the accepted
   certificates/classic_util_list/ClassicListOps.v, re-bound to this export).  Features: core mem uniq (universe instance List_inst1) *)
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedClassicInterferenceBoundFpApa.
From FoundationCertificates Require Import PropSPropFoundation LogicalRelation
  SubadditivityNatCorrespondence ClassicInterferenceBoundFpApaBase.

Module I := ImportedClassicInterferenceBoundFpApa.

(** Sequences are related to Lean lists through an element conversion [c]
    (the identity for identified carriers, the pair conversion for pairs):
    [ClListRel c sR sL := Lean.eq (cl_map c sR) sL].  Every operation lemma
    relates the MathComp operation on [sR] to the Lean operation on the
    converted list, by structural induction; the Lean side is unfolded one
    constructor at a time by conversion only. *)

Lemma cl1_nat_logic nR nL : SubNatRel nR nL -> Logic.eq nL (sub_nat_to_imported nR).
Proof. intro H. exact (Logic.eq_sym (imported_eq_to_coq_eq _ _ H)). Qed.

Lemma cl1_nat_input nR nL : SubNatRel nR nL -> Logic.eq (sub_nat_to_rocq nL) nR.
Proof. intro H. rewrite (cl1_nat_logic _ _ H). exact (sub_nat_rocq_roundtrip nR). Qed.

Lemma cl1_lean_eq (A : Type) (x y : A) : Logic.eq x y -> Lean.eq x y.
Proof. exact (coq_eq_to_imported_eq x y). Qed.

(* ------------------------------------------------------------------ *)
(** * Conversions *)

Fixpoint cl1_map {A B : Type} (c : A -> B) (s : seq A) : I.List_inst1 B :=
  match s with [::] => I.List_nil_inst1 B | x :: s' => I.List_cons_inst1 B (c x) (cl1_map c s') end.

Fixpoint cl1_unmap {A B : Type} (d : B -> A) (l : I.List_inst1 B) : seq A :=
  match l with I.List_nil_inst1 => [::] | I.List_cons_inst1 x l' => d x :: cl1_unmap d l' end.

Lemma cl1_unmap_map {A B : Type} (c : A -> B) (d : B -> A) (Hdc : forall x, Logic.eq (d (c x)) x) s :
  Logic.eq (cl1_unmap d (cl1_map c s)) s.
Proof. elim: s => [|x s IH] //=. by rewrite Hdc IH. Qed.

Lemma cl1_map_unmap {A B : Type} (c : A -> B) (d : B -> A) (Hcd : forall y, Logic.eq (c (d y)) y) l :
  Logic.eq (cl1_map c (cl1_unmap d l)) l.
Proof. induction l as [|y l IH]; first reflexivity. cbn. by rewrite Hcd IH. Qed.

Definition ClListRel1 {A B : Type} (c : A -> B) (sR : seq A) (sL : I.List_inst1 B) : SProp := Lean.eq (cl1_map c sR) sL.

Lemma cl1_list_logic {A B} (c : A -> B) sR sL : ClListRel1 c sR sL -> Logic.eq sL (cl1_map c sR).
Proof. intro H. exact (Logic.eq_sym (imported_eq_to_coq_eq _ _ H)). Qed.

Lemma cl1_forall_list {A B : Type} (c : A -> B) (d : B -> A) (Hcd : forall y, Logic.eq (c (d y)) y)
    (PR : seq A -> Prop) (PL : I.List_inst1 B -> SProp) :
  (forall sR sL, ClListRel1 c sR sL -> PropSPropRel (PR sR) (PL sL)) ->
  PropSPropRel (forall s, PR s) (forall s, PL s).
Proof.
  intro H. apply prop_sprop_rel_intro.
  - intros HR sL.
    exact (prop_to_sprop _ _ (H _ _ (cl1_lean_eq _ _ _ (cl1_map_unmap c d Hcd sL))) (HR _)).
  - intro HL. apply strictly_inhabits. intro sR.
    exact (sprop_to_prop _ _ (H sR (cl1_map c sR) (@Lean.eq_refl _ _)) (HL _)).
Qed.


(* ------------------------------------------------------------------ *)
(** * Membership, uniqueness, index (eqTypes) *)

Section Eq.
Variables (A : eqType) (B : Type) (c : A -> B) (d : B -> A).
Hypothesis Hdc : forall x, Logic.eq (d (c x)) x.
Hypothesis Hcd : forall y, Logic.eq (c (d y)) y.

Lemma cl1_c_inj x y : Logic.eq (c x) (c y) -> Logic.eq x y.
Proof. move=> E. by rewrite -(Hdc x) -(Hdc y) E. Qed.

Definition cl1_false_elim_s (Q : SProp) (H : is_true false) : Q :=
  match (Bool.diff_false_true H) return Q with end.

Fixpoint cl1_mem_forward (x : A) (s : seq A) {struct s} : x \in s -> I.List_Mem_inst1 B (c x) (cl1_map c s) :=
  match s as s0 return x \in s0 -> I.List_Mem_inst1 B (c x) (cl1_map c s0) with
  | [::] => fun H => cl1_false_elim_s _ H
  | y :: s' =>
      match @eqP A x y in reflect _ b return (b || (x \in s')) -> I.List_Mem_inst1 B (c x) (I.List_cons_inst1 B (c y) (cl1_map c s')) with
      | ReflectT E => fun _ =>
          match E in Logic.eq _ z return I.List_Mem_inst1 B (c x) (I.List_cons_inst1 B (c z) (cl1_map c s')) with
          | Logic.eq_refl => I.List_Mem_head_inst1 B (c x) _
          end
      | ReflectF _ => fun H => I.List_Mem_tail_inst1 B (c x) (c y) _ (cl1_mem_forward x s' H)
      end
  end.

Fixpoint cl1_mem_backward (a : B) (l : I.List_inst1 B) (H : I.List_Mem_inst1 B a l) : StrictlyInhabited (d a \in cl1_unmap d l) :=
  match H with
  | I.List_Mem_head_inst1 l' => strictly_inhabits (mem_head (d a) (cl1_unmap d l'))
  | I.List_Mem_tail_inst1 y l' Ht =>
      match cl1_mem_backward a l' Ht with
      | strictly_inhabits Hm => strictly_inhabits (introT orP (or_intror Hm) : d a \in d y :: cl1_unmap d l')
      end
  end.

Lemma cl1_mem_rel x s : PropSPropRel (x \in s) (I.List_Mem_inst1 B (c x) (cl1_map c s)).
Proof.
  apply prop_sprop_rel_intro; first exact (cl1_mem_forward x s).
  intro H. have S := cl1_mem_backward _ _ H. rewrite Hdc (cl1_unmap_map c d Hdc) in S. exact S.
Qed.

Lemma cl1_mem_rel_list x s sL : ClListRel1 c s sL -> PropSPropRel (x \in s) (I.List_Mem_inst1 B (c x) sL).
Proof. intro H. destruct H. exact (cl1_mem_rel x s). Qed.

Lemma cl1_notin_rel x s sL : ClListRel1 c s sL ->
  PropSPropRel (is_true (x \notin s)) (I.Not (I.List_Mem_inst1 B (c x) sL)).
Proof.
  intro H. have M := cl1_mem_rel_list x s sL H. apply prop_sprop_rel_intro.
  - move=> /negP N HL. exact (ct_coq_false_to_target (N (sprop_to_prop _ _ M HL))).
  - intro N. apply strictly_inhabits. apply/negP => Hm.
    exact (interpret_strict _ (ct_target_false_to_strict (N (prop_to_sprop _ _ M Hm)))).
Qed.

End Eq.

Section EqU.
Variables (A : eqType) (B : Type) (c : A -> B) (d : B -> A).
Hypothesis Hdc : forall x, Logic.eq (d (c x)) x.
Hypothesis Hcd : forall y, Logic.eq (c (d y)) y.

Fixpoint cl1_uniq_forward (s : seq A) : uniq s -> I.List_Nodup_inst1 B (cl1_map c s).
Proof.
  destruct s as [|x s]; cbn.
  - intros _. exact (I.List_Pairwise_nil_inst1 B (I.Ne B)).
  - intro H. destruct (andb_prop _ _ H) as [Hx Hs]. apply I.List_Pairwise_cons_inst1.
    + intros y Hy Exy.
      have Hy' := interpret_strict _ (cl1_mem_backward A B d _ _ Hy).
      rewrite (cl1_unmap_map c d Hdc) in Hy'.
      have E := imported_eq_to_coq_eq _ _ Exy. rewrite -E Hdc in Hy'.
      have F : Logic.False by rewrite Hy' in Hx.
      exact (ct_coq_false_to_target F).
    + exact (cl1_uniq_forward s Hs).
Defined.

Lemma cl1_uniq_backward (l : I.List_inst1 B) : I.List_Nodup_inst1 B l -> StrictlyInhabited (uniq (cl1_unmap d l)).
Proof.
  intro H. induction H as [|y l Hpair Htail IH].
  - exact (strictly_inhabits (Logic.eq_refl true)).
  - destruct IH as [IHu]. apply strictly_inhabits. rewrite /= IHu andbT. apply/negP => Hm.
    have Hm' := cl1_mem_forward A B c _ _ Hm. rewrite (cl1_map_unmap c d Hcd) Hcd in Hm'.
    exact (interpret_strict _ (ct_target_false_to_strict (Hpair y Hm' (@Lean.eq_refl _ _)))).
Qed.

Lemma cl1_uniq_rel s : PropSPropRel (uniq s) (I.List_Nodup_inst1 B (cl1_map c s)).
Proof.
  apply prop_sprop_rel_intro; first exact (cl1_uniq_forward s).
  intro H. have S := cl1_uniq_backward _ H. rewrite (cl1_unmap_map c d Hdc) in S. exact S.
Qed.

Lemma cl1_uniq_rel_list s sL : ClListRel1 c s sL -> PropSPropRel (uniq s) (I.List_Nodup_inst1 B sL).
Proof. intro H. destruct H. exact (cl1_uniq_rel s). Qed.


End EqU.

