From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedService.

Check ImportedService.Prosa_Behavior_Service_scheduled_at.
Check ImportedService.Prosa_Behavior_Service_service_at.
Check ImportedService.Prosa_Behavior_Service_receives_service_at.
Check ImportedService.Prosa_Behavior_Service_service_during.
Check ImportedService.Prosa_Behavior_Service_service.
Check ImportedService.Prosa_Behavior_Service_completed_by.
Check ImportedService.Prosa_Behavior_Service_completes_at.
Check ImportedService.Prosa_Behavior_Service_job_response_time_bound.
Check ImportedService.Prosa_Behavior_Service_job_meets_deadline.
Check ImportedService.Prosa_Behavior_Service_pending.
Check ImportedService.Prosa_Behavior_Service_pending_earlier_and_at.
Check ImportedService.Prosa_Behavior_Service_remaining_cost.

Check ImportedService.Prosa_Validation_ServiceInterface_scheduledAtProjection.
Check ImportedService.Prosa_Validation_ServiceInterface_serviceAtProjection.
Check ImportedService.Prosa_Validation_ServiceInterface_receivesServiceAtProjection.
Check ImportedService.Prosa_Validation_ServiceInterface_serviceDuringProjection.
Check ImportedService.Prosa_Validation_ServiceInterface_serviceProjection.
Check ImportedService.Prosa_Validation_ServiceInterface_completedByProjection.
Check ImportedService.Prosa_Validation_ServiceInterface_completesAtProjection.
Check ImportedService.Prosa_Validation_ServiceInterface_jobResponseTimeBoundProjection.
Check ImportedService.Prosa_Validation_ServiceInterface_jobMeetsDeadlineProjection.
Check ImportedService.Prosa_Validation_ServiceInterface_pendingProjection.
Check ImportedService.Prosa_Validation_ServiceInterface_pendingEarlierAndAtProjection.
Check ImportedService.Prosa_Validation_ServiceInterface_remainingCostProjection.

Check ImportedService.Prosa_Validation_ScheduleInterface_coreEnumeration.
Check ImportedService.Prosa_Validation_ScheduleInterface_production_scheduled_in_eq_true_iff.
Check ImportedService.Prosa_Validation_ScheduleInterface_production_service_in_as_list_sum.
