From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedReady.

Check ImportedReady.Prosa_Behavior_Ready_JobReady.
Check ImportedReady.Prosa_Behavior_Ready_JobReady_mk.
Check ImportedReady.Prosa_Behavior_Ready_JobReady_job_ready.
Check ImportedReady.Prosa_Behavior_Ready_JobReady_ready_implies_pending.
Check ImportedReady.Prosa_Behavior_Ready_backlogged.
Check ImportedReady.Prosa_Behavior_Ready_jobs_come_from_arrival_sequence.
Check ImportedReady.Prosa_Behavior_Ready_jobs_must_arrive_to_execute.
Check ImportedReady.Prosa_Behavior_Ready_jobs_must_be_ready_to_execute.
Check ImportedReady.Prosa_Behavior_Ready_completed_jobs_dont_execute.
Check ImportedReady.Prosa_Behavior_Ready_valid_schedule.

Check ImportedReady.Prosa_Validation_ReadyInterface_backloggedProjection.
Check ImportedReady.Prosa_Validation_ReadyInterface_jobsComeFromArrivalSequenceProjection.
Check ImportedReady.Prosa_Validation_ReadyInterface_jobsMustArriveToExecuteProjection.
Check ImportedReady.Prosa_Validation_ReadyInterface_jobsMustBeReadyToExecuteProjection.
Check ImportedReady.Prosa_Validation_ReadyInterface_completedJobsDontExecuteProjection.
Check ImportedReady.Prosa_Validation_ReadyInterface_validScheduleProjection.
