From LeanImport Require Import Lean.
Require Import ImportedEasy93.

Check Prosa_Behavior_Arrival_sequence_arrival_sequence.
Print Prosa_Behavior_Arrival_sequence_arrival_sequence.
Check Prosa_Behavior_Arrival_sequence_arrivals_at.
Print Prosa_Behavior_Arrival_sequence_arrivals_at.
Check Prosa_Behavior_Arrival_sequence_arrives_at.
Print Prosa_Behavior_Arrival_sequence_arrives_at.
Check Prosa_Behavior_Arrival_sequence_arrives_in.
Print Prosa_Behavior_Arrival_sequence_arrives_in.
Check Prosa_Behavior_Arrival_sequence_has_arrived.
Print Prosa_Behavior_Arrival_sequence_has_arrived.
Check Prosa_Behavior_Arrival_sequence_arrived_before.
Print Prosa_Behavior_Arrival_sequence_arrived_before.
Check Prosa_Behavior_Arrival_sequence_arrived_between.
Print Prosa_Behavior_Arrival_sequence_arrived_between.
Check Prosa_Behavior_Arrival_sequence_consistent_arrival_times.
Print Prosa_Behavior_Arrival_sequence_consistent_arrival_times.
Check Prosa_Behavior_Arrival_sequence_arrival_sequence_uniq.
Print Prosa_Behavior_Arrival_sequence_arrival_sequence_uniq.
Check Prosa_Behavior_Arrival_sequence_valid_arrival_sequence.
Print Prosa_Behavior_Arrival_sequence_valid_arrival_sequence.
Check Prosa_Behavior_Arrival_sequence_arrivals_between.
Print Prosa_Behavior_Arrival_sequence_arrivals_between.
Check Prosa_Behavior_Arrival_sequence_arrivals_up_to.
Print Prosa_Behavior_Arrival_sequence_arrivals_up_to.
Check Prosa_Behavior_Arrival_sequence_arrivals_before.
Print Prosa_Behavior_Arrival_sequence_arrivals_before.
