From FoundationCertificates Require Import ClassicJitterBertognaEdfCorrespondence.
Set Printing Width 1000.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_tsk_other_in_ts_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_tsk_other_in_ts_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_tsk_other_in_ts_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_R_other_ge_cost_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_R_other_ge_cost_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_R_other_ge_cost_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_workload_bounds_interference_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_workload_bounds_interference_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_workload_bounds_interference_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_specific_bound_holds_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_specific_bound_holds_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_specific_bound_holds_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_too_much_interference_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_too_much_interference_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_too_much_interference_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_interference_by_different_tasks_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_interference_by_different_tasks_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_interference_by_different_tasks_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_all_previous_jobs_complete_by_their_period_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_all_previous_jobs_complete_by_their_period_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_all_previous_jobs_complete_by_their_period_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_all_cpus_are_busy_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_all_cpus_are_busy_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_all_cpus_are_busy_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_interference_on_all_cpus_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_interference_on_all_cpus_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_interference_on_all_cpus_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_interference_in_non_full_processors_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_interference_in_non_full_processors_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_interference_in_non_full_processors_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_minimum_exceeds_interference_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_minimum_exceeds_interference_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_minimum_exceeds_interference_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_sum_exceeds_total_interference_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_sum_exceeds_total_interference_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_sum_exceeds_total_interference_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_edf_exists_task_that_exceeds_bound_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_edf_exists_task_that_exceeds_bound_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_edf_exists_task_that_exceeds_bound_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN ResponseTimeAnalysisEDFJitter_bertogna_cirinei_response_time_bound_edf_correspondence". exact Logic.I. Qed.
Print Assumptions ResponseTimeAnalysisEDFJitter_bertogna_cirinei_response_time_bound_edf_correspondence.
Goal Logic.True. idtac "AUDIT_END ResponseTimeAnalysisEDFJitter_bertogna_cirinei_response_time_bound_edf_correspondence". exact Logic.I. Qed.

Goal Logic.True. idtac "AUDIT_BEGIN cbt_forall_par". exact Logic.I. Qed.
Print Assumptions cbt_forall_par.
Goal Logic.True. idtac "AUDIT_END cbt_forall_par". exact Logic.I. Qed.
